<div class="container">
    <div class="row">
        <div class="col-md-8">
            <video style="margin: auto;" id="preview"></video>
        </div>
        <div class="col-md-4">
            <?php
            $admin = \Module\user\Model\Admin::getCurentUser(true);
            if ($admin == null) {
                header("Location: /dashboard/");
            }
            $CodeQr = new \Model\CodeQR($admin->Username);
            $ds = $CodeQr->GetCodes();
            ?>
            <div id="listcode">

            </div>
        </div>
    </div>
</div>
<div class="clearfix" ></div>
<div class="btn-group btn-group-toggle" data-toggle="buttons">
    <label class="btn btn-primary active">
        <input type="radio" name="options" value="0" autocomplete="off" checked> Camera 1
    </label>
    <label class="btn btn-primary ">
        <input type="radio" name="options" value="1" autocomplete="off" checked> Camera 2
    </label>
    <label class="btn btn-secondary">
        <input type="radio" name="options" value="2" autocomplete="off"> Camera 3
    </label>
</div>
<script src="/theme/thanhminhduc/public/qrcode.js?v=<?php echo time(); ?>" type="text/javascript"></script>

