<ol class="breadcrumb" >
    <li><a href="" class="" >Danh Sách Sản Phẩm </a></li>
</ol>
<?php
$tong = 0;

if (Module\user\Model\Admin::getCurentUser(TRUE)->Groups == Module\user\Model\Admin::Admin || Module\user\Model\Admin::getCurentUser(TRUE)->Groups == Module\user\Model\Admin::SuperAdmin) {
    $SanPhams = Module\sanpham\Model\SanPham::SanPhamsPT("", 1, 200, $tong);
} else {
    $SanPhams = Module\sanpham\Model\SanPham::SanPhamsDaiLyPT("", 1, 200, $tong);
}
?>
<form action="" method="POST" enctype="multipart/form-data" >
    <div class="modal fade" id="ThemSanPham">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Thêm Sản Phẩm </h4>
                </div>
                <div class="modal-body">
                    <?php
                    \Module\sanpham\Model\SanPhamForm::DanhMuc()->renderHTML();
                    ?>
                    <div class="form-group">
                        <label for="">Số Lượng </label>
                        <input type="text" class="form-control" name="SoLuong" value="10" placeholder="Số Lượng">
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" name="TaoMaSanPham" value="TaoMaSanPham" class="btn btn-primary">Thêm Sản Phẩm</button>
                </div>
            </div>
        </div>
    </div>
</form>


<div class="container-fluid " >
    <div class="box box-primary" >
        <div class="box-header " >
            <div class="box-tools" >
                <?php
                if (Module\user\Model\Admin::CheckQuyen([Module\user\Model\Admin::Admin, Module\user\Model\Admin::SuperAdmin])) {
                    ?>
                    <a class="btn btn-primary btn-sm" data-toggle="modal" href='#ThemSanPham'>
                        <i class="fa fa-plus" ></i>
                        Thêm Sản Phẩm
                    </a>
                    <?php
                }
                ?>
            </div>
            <h3  class="box-title" >
                Danh Sách Sản Phẩm (<?php echo $tong; ?>)
            </h3>
        </div>
        <div class="box-body table-responsive" >


            <table class="table table-bordered dataTable " id="data"   >
                <thead>
                    <tr class="bg-blue">
                        <th></th>
                        <th>#</th>
                        <th>Code</th>
                        <th>Name</th>
                        <th>Tem Bảo Hành</th>
                        <th>Danh Mục</th>
                        <th>Tình Trạng</th>
                        <th>Đại Lý/NPP</th>
                        <?php
                        if (Module\user\Model\Admin::CheckQuyen([Module\user\Model\Admin::Admin, Module\user\Model\Admin::SuperAdmin])) {
                            ?>
                            <th>Wf</th>
                            <?php
                        }
                        ?>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($SanPhams as $k => $sp) {
                        $_sp = new Module\sanpham\Model\SanPham($sp);
                        ?>
                        <tr>
                            <td style="width: 100px;" >
                                <a href="/sanpham/taosanpham/edit/<?php echo $_sp->Id ?>/" class="btn btn-sm btn-primary" >Xem</a>
                                <?php
                                if ($_sp->Wfstatus == 0 && Module\user\Model\Admin::CheckQuyen([Module\user\Model\Admin::DaiLy])) {
                                    ?>
                                    <a onclick="return  confirm('Tôi Đã Nhận Sản Phẩm Này.')" href="/sanpham/taosanpham/nhansp/<?php echo $_sp->Id ?>/" class="btn btn-sm btn-success" >Nhận</a>
                                    <?php
                                }
                                ?>

                            </td>
                            <td style="width: 50px;" ><?php echo $k + 1; ?></td>
                            <td style="width: 150px;" ><?php echo $_sp->Code ?></td>
                            <td><?php echo $_sp->Name ?></td>
                            <td style="width: 150px;" >
                                <a href="/sanpham/temsanpham/detailbysanpham/<?php echo $_sp->TemBaoHang()->Code; ?>" >Tem Bảo Hành</a>
                            </td>
                            <td style="width: 200px;" ><?php echo $_sp->DanhMuc()->Name; ?></td>
                            <td style="width: 200px;" ><?php echo $_sp->TinhTrang(); ?></td>
                            <td style="width: 200px;" ><?php echo $_sp->DaiLy()->Name; ?></td>
                            <?php
                            if (Module\user\Model\Admin::CheckQuyen([Module\user\Model\Admin::Admin, Module\user\Model\Admin::SuperAdmin])) {
                                $ws = ["Đang Ở Công Ty", "Đã Nhận"]
                                ?>
                                <th><?php echo $ws[$_sp->Wfstatus]; ?></th>
                                <?php
                            }
                            ?>
                        </tr>
                        <?php
                    }
                    ?>
                </tbody>

            </table>
        </div>
    </div>

</div>