<script type="text/javascript" >
    app.controller("projectController", function($scope, $http) {
        $scope.projectInnit = function( ) {
            $http.get("/project/api/projects/").then(function(res) {
                $scope._Project = res.data;
            });
        }
    });
</script>
<div class="row " ng-controller="projectController" ng-init="projectInnit()" >
    <section class="col-md-12 pb-10" >
        <div class="connectedSortable" >

            <form method="POST" action="/project/index/create/" enctype="multipart/form-data" >
                <div class="modal fade" data-backdrop="false"  id="ThemOptions">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">Thêm Dự Án</h4>
                            </div>
                            <div class="modal-body">
                                <?php
                                \Module\project\Model\ProjectForm::Name()->renderHTML();
                                \Module\project\Model\ProjectForm::Email()->renderHTML();
                                \Module\project\Model\ProjectForm::Phone()->renderHTML();
                                \Module\project\Model\ProjectForm::Address()->renderHTML();
                                ?>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                                <button type="submit" name="btnsave" class="btn btn-primary">Thêm</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <div class="box box-primary" >
                <div class="box-header" >
                    <a class="btn btn-primary pull-right" data-toggle="modal" href='#ThemOptions'>Thêm</a>
                    <h3 class="box-title" >Dự Án</h3>
                </div>
                <div class="box-body table-responsive" >
                    <table class="table table-bordered" >
                        <thead>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Tên Dự Án</th>
                                <th>Email Liên Hệ</th>
                                <th>SĐT Liên Hệ</th>
                                <th>Địa Chỉ</th>
                                <th>Tình Trạng</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="item in _Project" >
                                <td>
                                    <a href="/project/index/edit/{{item.Id}}" class="" >
                                        Xem
                                    </a> |
                                    <a href="/project/index/delete/{{item.Id}}" style="color: red;" >
                                        Xóa
                                    </a>

                                </td>
                                <td>{{$index + 1}}</td>
                                <td><a href="/project/dashboard/SetCurentProject/{{item.Id}}"  >{{item.Name}}</a></td>
                                <td>{{item.Email}}</td>
                                <td>{{item.Phone}}</td>
                                <td>{{item.Address}}</td>
                                <td>{{item.Status}}</td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Tên Dự Án</th>
                                <th>Email Liên Hệ</th>
                                <th>SĐT Liên Hệ</th>
                                <th>Địa Chỉ</th>
                                <th>Tình Trạng</th>
                            </tr>
                        </tfoot>

                    </table>
                </div>
            </div>

        </div>
    </section>
</div>