<?php
$pageNumber = 1;
$Number = 20;
$Tong = 0;
datatable\ZendData::$IsDebug = true;
$KhachHangs = \Module\khachhang\Model\KhachHangTieuDung::KhachHangTieuDungsPt($pageNumber, $Number, $Tong);
?>
<script type="text/javascript" >
    app.controller("optionController", function($scope, $http) {
        $scope.optionInnit = function( ) {
            $http.get("/option/api/options/").then(function(res) {
            });
        }
    });
</script>
<ol class="breadcrumb">
    <li>
        <a href="/dashboard/">Dashboad</a>
    </li>
    <li class="active">Khách Hàng Tiêu Dùng</li>
</ol>
<div class="row " >
    <section class="col-md-12 pb-10 mt-20" >
        <div class=" " >
            <div class="box box-primary" >
                <div class="box-header">
                    <h3 class="box-title" >Danh Sách Khách Hàng Tiêu Dùng</h3>
                </div>
                <div class="box-body table-responsive" >
                    <table class="table table-bordered " id="data"   >
                        <thead>
                            <tr>
                                <th class="text-center" >#</th>
                                <th>Họ & Tên</th>
                                <th>SĐT</th>
                                <th>Địa Chỉ</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($KhachHangs as $index => $kh) {
                                $_Kh = new Module\khachhang\Model\KhachHangTieuDung($kh);
                                ?>
                                <tr>
                                    <td class="text-center" ><?php echo $index + 1; ?></td>
                                    <td><?php echo $_Kh->Name; ?></td>
                                    <td><?php echo $_Kh->Phone; ?></td>
                                    <td><?php echo $_Kh->DiaChi; ?></td>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th class="text-center" style="width: 50px;" >#</th>
                                <th style="width: 300px;" >Họ & Tên</th>
                                <th>SĐT</th>
                                <th>Địa Chỉ</th>
                            </tr>
                        </tfoot>

                    </table>
                    <?php
                    ?>
                </div>
            </div>

        </div>
    </section>
</div>