<?php
$KhachHang = new Module\khachhang\Model\KhachHang();
?>
<ol class="breadcrumb">
    <li>
        <a href="/dashboard/">Dashboard</a>
    </li>
    <li>
        <a href="/khachhang/">Đại Lý Bán Hàng</a>
    </li>
    <li class="active">Thêm</li>
</ol>
<div class="container" >
    <div class="row" >
        <div class="clearfix" ></div>
        <section class="pb-10" >
            <form action="" method="POST" enctype="multipart/form-data" >
                <div class="" >
                    <div class="box box-solid">
                        <div class=" box-header bg-blue-gradient">
                            <h3 class="box-title">Thêm Khách Hàng</h3>
                            <!-- tools box -->
                        </div>
                        <div class="box-body">
                            <fieldset>
                                <legend>Thông tin hành chính</legend>
                                <div class="row pt-15">
                                    <div class="col-md-4">
                                        <a class="pull-right btn btn-primary btn-xs" data-toggle="modal" href='#huongDan'>
                                            <i class="fa fa-question" ></i>
                                        </a>
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::Id($KhachHang->Id)->render();
                                        Module\khachhang\Model\KhachHangForm::Code($KhachHang->Code)->renderHTML();
                                        ?>
                                        <div class="modal fade" id="huongDan">
                                            <div class="modal-dialog modal-lg">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                        <h3 class="modal-title">Hướng Dẫn</h3>
                                                    </div>
                                                    <div class="modal-body center-block">
                                                        <div class="text-center"  >
                                                            <img style="margin: auto;" class="img img-responsive" src="/public/duongdan/MaKhachHang.JPG" alt="hướng Dẫn"/>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-default" data-dismiss="modal">Thoát</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::Name($KhachHang->Name)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::DienThoai($KhachHang->DienThoai)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4 hidden">
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::Parents($KhachHang->Parents)->renderHTML();
                                        ?>
                                    </div>

                                    <div class="col-md-4">
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::LoaiHinhKinhDoanh('XD')->renderHTML();
                                        ?>
                                    </div>


                                    <div class="col-md-4">
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::LaChuKinhDoanh(1)->renderHTML();
                                        ?>
                                    </div>

                                    <div class="col-md-4 hidden">
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::DiDong($KhachHang->DiDong)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4 hidden">
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::Zalo($KhachHang->Zalo)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4 hidden">
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::MaSoThue($KhachHang->MaSoThue)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4 hidden">
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::NhomHangKinhDoanh($KhachHang->NhomHangKinhDoanh)->renderHTML();
                                        ?>
                                    </div>

                                </div>
                            </fieldset>
                            <fieldset>
                                <legend>Địa Chỉ</legend>
                                <div class="row">

                                    <div class="col-md-4 hidden">
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::KhuVuc($KhachHang->KhuVuc)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::TinhThanh(32)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::QuanHuyen(null, 32)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::DiaChi($KhachHang->DiaChi)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-12">
                                        <?php
                                        Module\khachhang\Model\KhachHangForm::DiaChiGiaoHang($KhachHang->DiaChi)->renderHTML();
                                        ?>
                                    </div>
                                </div>
                            </fieldset>
                            <fieldset hidden="" >
                                <legend>Thông Tin Thanh Toán</legend>
                                <div class="row">
                                    <div class="col-md-4">
                                        <?php
                                        Module\khachhang\Model\KhachHangThanhToanForm::TenCongTy($KhachHang->KhachHangThanhToan()->TenCongTy)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        Module\khachhang\Model\KhachHangThanhToanForm::MaSoThue($KhachHang->KhachHangThanhToan()->MaSoThue)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        Module\khachhang\Model\KhachHangThanhToanForm::DiaChi($KhachHang->KhachHangThanhToan()->DiaChi)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        Module\khachhang\Model\KhachHangThanhToanForm::STK($KhachHang->KhachHangThanhToan()->STK)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        Module\khachhang\Model\KhachHangThanhToanForm::NganHang($KhachHang->KhachHangThanhToan()->NganHang)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4 hidden">
                                        <?php
                                        Module\khachhang\Model\KhachHangThanhToanForm::Fax($KhachHang->KhachHangThanhToan()->Fax)->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-12">
                                        <?php
                                        Module\khachhang\Model\KhachHangThanhToanForm::GhiChu($KhachHang->KhachHangThanhToan()->GhiChu)->renderHTML();
                                        ?>
                                    </div>
                                </div>
                            </fieldset>
                        </div>
                        <div class="box-footer" >
                            <?php
                            Module\rmm\Model\RoomForm::btnSave()->render();
                            ?>
                        </div>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>
