<?php
$link = "/public/phpqrcode/index.php?data=" . Root_URL . "baohanh/" . $temSanPham->Code;
?>
<ol class="breadcrumb">
    <li>
        <a href="#">Dashboard</a>
    </li>
    <li>
        <a href="/sanpham/temsanpham/">Danh Sách Tem</a>
    </li>
    <li class="active">Tem Bảo Hành</li>
</ol>
<div class="" >
    <div class=""  >
        <section class="col-md-12 pb-10" >

            <div class="modal fade" id="MaBaoHanh">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title">QR code</h4>
                        </div>
                        <div class="modal-body">
                            <img style="width: 100%" src="<?php echo $link; ?>" class="img img-responsive"  >
                            <a href="<?php echo Root_URL . "baohanh/" . $temSanPham->Code; ?>"
                               class="" >Xem -->></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="" >
                <form action="" method="POST" enctype="multipart/form-data" >
                    <div class="box box-primary">
                        <div class="box-header">
                            <h3 class="box-title">Tem Bảo Hành</h3>
                        </div>
                        <div class="box-body">
                            <div class="col-md-6" >
                                <fieldset>
                                    <legend>Thông Tin Bảo Hành</legend>
                                    <?php
                                    \Module\sanpham\Model\TemSanPhamForm::Id($temSanPham->Id)->render();
                                    \Module\sanpham\Model\TemSanPhamForm::Name($temSanPham->Name)->renderHTML();
                                    \Module\sanpham\Model\TemSanPhamForm::MaSanPham($temSanPham->MaSanPham, false)->renderHTML();
                                    ?>
                                    <div class="row" >
                                        <div class="col-md-4">
                                            <?php
                                            \Module\sanpham\Model\TemSanPhamForm::NgayBatDau($temSanPham->NgayBatDau)->renderHTML();
                                            ?>
                                        </div>
                                        <div class="col-md-4">
                                            <?php
                                            \Module\sanpham\Model\TemSanPhamForm::ThangKetThuc($temSanPham->ThangKetThuc)->renderHTML();
                                            ?>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="">Ngày Kết Thúc</label>
                                                <input type="text" readonly="" value="<?php echo $temSanPham->NgayKetThuc() ?>" class="form-control" >
                                            </div>

                                        </div>

                                    </div>
                                    <?php
                                    \Module\sanpham\Model\TemSanPhamForm::KhachHangTieuDung($temSanPham->KhachHangTieuDung, true)->renderHTML();
                                    \Module\sanpham\Model\TemSanPhamForm::Status($temSanPham->Status)->renderHTML();
                                    ?>
                                    <div class="btn-group" >
                                        <a class="btn btn-primary" data-toggle="modal" href='#ThemTemPhu'>Thêm Tem Phụ</a>
                                        <a class="btn btn-primary" data-toggle="modal" href='#MaBaoHanh'>Mã QR Code</a>
                                    </div>
                                </fieldset>
                                <fieldset>
                                    <legend>Thông Tin Khách Hàng Tiêu Dùng</legend>
                                    <div class="row" >
                                        <div class="col-md-6">
                                            <?php
                                            Module\khachhang\Model\KhachHangTieuDungForm::Id($khachHang->Id)->render();
                                            Module\khachhang\Model\KhachHangTieuDungForm::Name($khachHang->Name)->renderHTML();
                                            ?>
                                        </div>
                                        <div class="col-md-6">
                                            <?php
                                            Module\khachhang\Model\KhachHangTieuDungForm::Phone($khachHang->Phone)->renderHTML();
                                            ?>
                                        </div>
                                        <div class="col-md-4">
                                            <?php
                                            Module\khachhang\Model\KhachHangTieuDungForm::KhuVuc($khachHang->KhuVuc)->renderHTML();
                                            ?>
                                        </div>
                                        <div class="col-md-4">
                                            <?php
                                            Module\khachhang\Model\KhachHangTieuDungForm::TinhThanh($khachHang->TinhThanh)->renderHTML();
                                            ?>
                                        </div>
                                        <div class="col-md-4">
                                            <?php
                                            Module\khachhang\Model\KhachHangTieuDungForm::QuanHuyen($khachHang->QuanHuyen, $khachHang->TinhThanh)->renderHTML();
                                            ?>
                                        </div>
                                    </div>
                                    <?php
                                    Module\khachhang\Model\KhachHangTieuDungForm::DiaChi($khachHang->DiaChi)->renderHTML();
                                    Module\khachhang\Model\KhachHangTieuDungForm::GhiChu($khachHang->GhiChu)->renderHTML();
                                    ?>
                                </fieldset>
                            </div>
                            <div class="col-md-6" >
                                <fieldset>
                                    <legend>Thông Tin Sản Phẩm</legend>
                                    <?php
                                    \Module\sanpham\Model\SanPhamForm::Id($temSanPham->SanPham()->Id)->render();
                                    \Module\sanpham\Model\SanPhamForm::Code($temSanPham->SanPham()->Code)->renderHTML();
                                    ?>
                                    <div class="">
                                        <button type="button" class="btn btn-sm pull-right" data-toggle="modal" data-target='#ChonSanPham'>Chọn Sản Phẩm</button>
                                        <?php
                                        \Module\sanpham\Model\SanPhamForm::Name($temSanPham->SanPham()->Name)->renderHTML();
                                        ?>
                                    </div>
                                    <?php
                                    \Module\sanpham\Model\SanPhamForm::Mota($temSanPham->SanPham()->Mota)->renderHTML();
                                    \Module\sanpham\Model\SanPhamForm::ChungLoaiSP($temSanPham->SanPham()->ChungLoaiSP)->renderHTML();
                                    \Module\sanpham\Model\SanPhamForm::DanhMuc($temSanPham->SanPham()->DanhMuc)->renderHTML();
                                    \Module\sanpham\Model\SanPhamForm::TinhTrang($temSanPham->SanPham()->TinhTrang)->renderHTML();
                                    \Module\sanpham\Model\SanPhamForm::MaDaiLy($temSanPham->SanPham()->MaDaiLy)->renderHTML();
                                    ?>
                                    <div class="form-group">
                                        <img src="<?php echo $temSanPham->SanPham()->HinhAnh; ?>?v=<?php echo time(); ?>"  style="height: 80px;" class="img img-responsive" >
                                        <label for="">Hình Sản Phẩm</label>
                                        <?php
                                        \Module\sanpham\Model\SanPhamForm::HinhAnh()->render();
                                        ?>
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                        <div class="box-footer text-right" >
                            <?php
                            Module\rmm\Model\RoomForm::btnSave()->render();
                            ?>

                        </div>
                    </div>
                </form>
            </div>
        </section>

    </div>
</div>
<div class="modal fade" id="ThemTemPhu">
    <form action="" method="POST" enctype="multipart/form-data" >
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Tem Bảo Hành Phụ</h4>
                </div>
                <div class="modal-body">
                    <?php
                    \Module\sanpham\Model\TemSanPhamForm::Name()->renderHTML();
                    \Module\sanpham\Model\TemSanPhamForm::MaSanPham()->renderHTML();
                    \Module\sanpham\Model\TemSanPhamForm::NgayBatDau(Date("d-m-Y", time()))->renderHTML();
                    \Module\sanpham\Model\TemSanPhamForm::ThangKetThuc()->renderHTML();
                    \Module\sanpham\Model\TemSanPhamForm::Status()->renderHTML();
                    \Module\sanpham\Model\TemSanPhamForm::Parents($temSanPham->Id, "", true)->renderHTML();
                    ?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" name="ThenTemPhu" value="them" class="btn btn-primary">Lưu</button>
                </div>
            </div>
        </div>
    </form>

</div>
<!-- cập nhật thông tin sản phna -->
<form action="" enctype="multipart/form-data" method="POST" >
    <div class="modal fade" id="ChonSanPham">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Chọn Model Sản Phẩm</h4>
                </div>
                <div class="modal-body">
                    <?php
                    echo $temSanPham->SanPham()->Id;
                    Module\option\Model\OptionForm::SelectGroups("Danh Mục Sản Phẩm", "Chon[MaDanhMuc]", "DanhMucVatTu")->renderHtml();
                    Module\option\Model\OptionForm::Hidden("Chon[MaSanPham]", $temSanPham->SanPham()->Id)->render();
                    ?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" name="ChonDanhMucSanPham" class="btn btn-primary">OK</button>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="clearfix">

</div>