<div class="login-box">
    <div class="login-box-body">
        <div class="center-block" >
            <img style="margin: auto;" src="/public/Logo2.svg" class="img img-responsive" >
            <h3 class="text-center" >Hệ Thống Quản Lý Tem Bảo Hành</h3>
        </div>
        <form action="" method="post">
            <div class="form-group has-feedback">
                <input type="text" name="Username" class="form-control" placeholder="Tài khoản">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" name="Password" class="form-control" placeholder="Mật khẩu">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="">
                <div class=" ">
                    <button type="submit" name="dangnhap" class="btn btn-primary btn-block ">Đăng Nhập</button>
                </div>
            </div>
        </form>
    </div>
</div>