<script type="text/javascript" >
    function onSignIn(googleUser) {
        if (window.confirm("Bạn có muốn đăng nhập bằng tài khoản google?") == false) {
            return;
        }
        var id_token = googleUser.getAuthResponse().id_token;

        var xhr = new XMLHttpRequest();
        xhr.open('POST', '/user/login/google/');
        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        xhr.onload = function() {
//            console.log('Signed in as: ' + xhr.responseText);
            window.location.href = "/dashboard/";
        };
        xhr.send('idtoken=' + id_token);
    }
</script>
<script src="https://apis.google.com/js/platform.js" async defer></script>
<div class="login-box">
    <div class="login-box-body">
        <div class="center-block" >
            <img style="margin: auto;" src="/public/Logo2.svg" class="img img-responsive" >
            <h3 class="text-center" >Hệ Thống Quản Lý Tem Bảo Hành</h3>
        </div>
        <form action="" method="post">
            <div class="form-group has-feedback">
                <input type="text" name="Username" class="form-control" placeholder="Tài khoản">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" name="Password" class="form-control" placeholder="Mật khẩu">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="">
                <div class=" ">
                    <button type="submit" name="dangnhap" class="btn btn-primary btn-block ">Đăng Nhập</button>
                </div>
            </div>
        </form>
        <div class="text-center">
            <br>
            <div>--Hoặc--</div>
            <br>
            <div class="g-signin2" data-onsuccess="onSignIn"></div>
        </div>

    </div>
</div>