<div class="login-box">
    <div class="login-box-body">
        <p class="login-box-msg">Đăng nhập hệ thống</p>
        <form action="" method="post">
            <div class="form-group has-feedback">
                <input type="text" name="Username" class="form-control" placeholder="Tài khoản">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" name="Password" class="form-control" placeholder="Mật khẩu">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="">
                <div class="form-group ">
                    <label>
                        <input type="checkbox"> Nhớ tài khoản
                    </label>
                </div><!-- /.col -->
                <div class=" ">
                    <button type="submit" name="dangnhap" class="btn btn-primary btn-block ">Đăng Nhập</button>
                </div><!-- /.col -->
            </div>
        </form>
    </div><!-- /.login-box-body -->
    <a href="/mlogin/quenmatkhau/">Quên Mật Khẩu?</a><br>
</div><!-- /.login-box -->