<div class="login-box">
    <div class="login-box-body">
        <?php
        $Alert = \Common\Alert::getAlert();
        if ($Alert) {
            ?> 
            <div class="alert alert-<?php echo $Alert["Type"] ?>" >
                <div><?php echo $Alert["Content"] ?></div>
            </div>
            <?php
        }
        ?>
        <div class="text-center">
            <a class="fa-2x" href="/app/"><b>NguyenVanDo</b>.net</a>
        </div>
        <p class="login-box-msg">Đăng nhập hệ thống</p>
        <form action="" method="post">
            <div class="form-group has-feedback">
                <input type="text" name="Username" class="form-control" placeholder="Tài khoản" />
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" name="Password" class="form-control" placeholder="Password" />
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" name="Key2fa" class="form-control" placeholder="Key2fa" />
                <span class="glyphicon glyphicon-cloud form-control-feedback"></span>
            </div>
            <div class="row ">
                <div class="col-xs-8 hidden">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox"> Remember Me
                        </label>
                    </div>
                </div> 
                <div class="col-xs-4"></div>
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Đăng nhập</button>
                </div> 
            </div>
        </form>
        <div class="social-auth-links text-center hidden">
            <p>- OR -</p>
            <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using Facebook</a>
            <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign in using Google+</a>
        </div>
        <br>
        <a href="/user/index/register/" class="pull-right" >Đăng Ký Thành Viên</a> 
        <a href="/user/index/resetpassword/" class="pull-left" >Quên Mật Khẩu</a> 
        <br>
    </div>
</div>