
<div class="register-box">
    <?php
    $alt = Common\Alert::getAlert();
    if ($alt) {
        ?> 
        <div class="alert alert-<?php echo $alt["Type"] ?>" ><?php echo $alt["Content"] ?></div>
        <?php
    }
    ?>
    <div class="register-box-body">
        <div class="text-center">
            <a class="fa-2x" href="/app/">
                <img src="[Logo]" class="img img-responsive" alt="[Website]" title="[Website]" >
            </a>
        </div>
        <h3 class="login-box-msg">Reset password</h3>
        <form action="" method="post">
            <div class="form-group has-feedback">
                <input type="email" required="required" name="Account[Email]" class="form-control" placeholder="Email" />
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <?php Model\Form::btnSend() ?>
                    <button type="submit"  name="" class="btn btn-primary btn-block btn-flat">Gửi</button>
                </div> 
            </div>
        </form>
        <div class="hidden social-auth-links text-center">
            <p class="text-center" >- OR -</p>
            <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign up using Facebook</a>
            <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign up using Google+</a>
        </div> 
    </div> 
</div> 