<script type="text/javascript" >
    app.controller("pixelfacebookController", function($scope, $http) {
        $scope.projectInnit = function( ) {
        }
        $scope.Save = function( ) {

        }

    });
</script>
<div class="row " ng-controller="pixelfacebookController"  >
    <section class="col-md-12 pb-10" >
        <div class="connectedSortable" >
            <div class="box box-primary" >
                <div class="box-header" >
                    <h3 class="box-title" >Cấu Hình pixell facebook</h3>
                </div>
                <div class="box-body table-responsive" >
                    <form action="" method="POST" enctype="multipart/form-data" >
                        <?php
                        Module\project\Model\PixelFacebookCode::pixelfacebook($pixelfacebook->TextValues)->renderHTML();
                        ?>
                        <button type="submit" name="Save" >Lưu</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>