<?php
$TrungTamBaoHanh;
?>
<ol class="breadcrumb">
    <li>
        <a href="/Dashboad/">Dashboad</a>
    </li>
    <li>
        <a href="/trungtambaohanh/index/">Trung Tâm Bảo Hành</a>
    </li>
    <li>
        <a href="/trungtambaohanh/index/">Sửa</a>
    </li>
</ol>
<div class="container-fluid" >
    <div class="" >
        <div class="clearfix" ></div>
        <section class="pb-10" >
            <form action=""  method="POST" enctype="multipart/form-data" >

                <div class="connectedSortable" >
                    <div class="box box-solid">
                        <div class=" box-header bg-blue-gradient">
                            <h3 class="box-title">Sửa Trung Tâm Bảo Hành</h3>
                            <!-- tools box -->
                        </div>
                        <div class="box-body">
                            <div class="row pt-15">
                                <div class="col-md-3">
                                    <?php
                                    Module\trungtambaohanh\Model\TrungTamBaoHanhForm::Id($TrungTamBaoHanh->Id)->render();
                                    Module\trungtambaohanh\Model\TrungTamBaoHanhForm::Name($TrungTamBaoHanh->Name)->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-3">
                                    <?php
                                    Module\trungtambaohanh\Model\TrungTamBaoHanhForm::Hotline($TrungTamBaoHanh->Hotline)->renderHTML();
                                    ?>
                                </div>

                                <div class="col-md-3">
                                    <?php
                                    Module\trungtambaohanh\Model\TrungTamBaoHanhForm::TenNhanVien($TrungTamBaoHanh->TenNhanVien)->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-3">
                                    <?php
                                    Module\trungtambaohanh\Model\TrungTamBaoHanhForm::UserId($TrungTamBaoHanh->UserId)->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-8">
                                    <?php
                                    Module\trungtambaohanh\Model\TrungTamBaoHanhForm::Address($TrungTamBaoHanh->Address)->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-4">
                                    <?php
                                    Module\trungtambaohanh\Model\TrungTamBaoHanhForm::KhuVuc($TrungTamBaoHanh->KhuVuc)->renderHTML();
                                    ?>
                                </div>
                            </div>
                        </div>
                        <div class="box-footer" >
                            <?php
                            Module\rmm\Model\RoomForm::btnSave()->render();
                            ?>
                        </div>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>
