<?php
$KhachHangs = \Module\trungtambaohanh\Model\TrungTamBaoHanh::TrungTamBaoHanhs();
?>
<ol class="breadcrumb">
    <li><a href="/dashboard/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active">Trung Tâm Bảo Hành</li>
</ol>
<script type="text/javascript" >
    app.controller("ttbhController", function($scope, $http) {
        $scope.ttbhInnit = function( ) {
            $http.get("/option/api/options/").then(function(res) {
            });
        }
    });
</script>
<div class="container-fluid  " ng-controller="ttbhController" >
    <section class="col-md-12 pb-10 " >
        <div class="connectedSortable" >
            <div class="box box-primary" >
                <div class="box-body  " >
                    <div class="btn-group pull-left" >
                        <?php
                        echo \Module\trungtambaohanh\Model\TrungTamBaoHanhForm::btnThem("Thêm Trung Tâm");
                        echo \Module\trungtambaohanh\Model\PhuLucSuaChuaForm::btnPhuLucSuaChua("Phụ Lục Sửa Chữa");
                        ?>
                    </div>
                    <table class="table table-striped table-bordered dataTable " id="data"   >
                        <thead>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Tên Trung Tâm</th>
                                <th>Hotline</th>
                                <th>Khu Vực</th>
                                <th>Địa Chỉ</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($KhachHangs as $index => $op) {
                                $_op = new \Module\trungtambaohanh\Model\TrungTamBaoHanh($op);
                                ?>
                                <tr>
                                    <td>
                                        <?php
                                        echo Module\trungtambaohanh\Model\TrungTamBaoHanhForm::Sua($_op->Id);
                                        echo Module\trungtambaohanh\Model\TrungTamBaoHanhForm::Xoa($_op->Id);
                                        ?>
                                    </td>
                                    <td><?php echo $index + 1 ?></td>
                                    <td><?php echo $_op->Name ?></td>
                                    <td><?php echo $_op->Hotline ?></td>
                                    <td><?php
                                        echo $_op->KhuVuc()->Name;
                                        ?></td>
                                    <td><?php echo $_op->Address; ?></td>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Tên Trung Tâm</th>
                                <th>Hotline</th>
                                <th>Khu Vực</th>
                                <th>Địa Chỉ</th>
                            </tr>
                        </tfoot>

                    </table>
                </div>
            </div>

        </div>
    </section>
</div>