<?php
$KhachHangs = \Module\trungtambaohanh\Model\TrungTamBaoHanh::TrungTamBaoHanhs();
?>
<script type="text/javascript" >
    app.controller("ttbhController", function($scope, $http) {
        $scope.ttbhInnit = function( ) {
            $http.get("/option/api/options/").then(function(res) {
            });
        }
    });
</script>
<div class="row " ng-controller="ttbhController" >
    <section class="col-md-12 mb-10" >
        <?php
        echo \Module\trungtambaohanh\Model\TrungTamBaoHanhForm::btnThem("Thêm Trung Tâm");
        echo \Module\trungtambaohanh\Model\PhuLucSuaChuaForm::btnPhuLucSuaChua("Phụ Lục Sửa Chữa");
        ?>
    </section>
    <section class="col-md-12 pb-10 mt-20" >
        <div class="connectedSortable" >
            <div class="box box-primary" >
                <div class="box-body table-responsive" >
                    <table class="table table-bordered dataTable " id="data"   >
                        <thead>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Tên Trung Tâm</th>
                                <th>Hotline</th>
                                <th>Khu Vực</th>
                                <th>Địa Chỉ</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($KhachHangs as $index => $op) {
                                $_op = new \Module\trungtambaohanh\Model\TrungTamBaoHanh($op);
                                ?>
                                <tr>
                                    <th>
                                        <?php
                                        echo Module\trungtambaohanh\Model\TrungTamBaoHanhForm::Sua($_op->Id);
                                        echo Module\trungtambaohanh\Model\TrungTamBaoHanhForm::Xoa($_op->Id);
                                        ?>

                                    </th>
                                    <th><?php echo $index + 1 ?></th>
                                    <th><?php echo $_op->Name ?></th>
                                    <th><?php echo $_op->Hotline ?></th>
                                    <th><?php echo $_op->KhuVuc()->Name ?></th>
                                    <th><?php echo $_op->Address; ?></th>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Tên Trung Tâm</th>
                                <th>Hotline</th>
                                <th>Khu Vực</th>
                                <th>Địa Chỉ</th>
                            </tr>
                        </tfoot>

                    </table>
                </div>
            </div>

        </div>
    </section>
</div>