<?php
$PhuLucSuaChuas = \Module\trungtambaohanh\Model\PhuLucSuaChua::PhuLucSuaChuas();
?>
<script type="text/javascript" >
    app.controller("ttbhController", function($scope, $http) {
        $scope.ttbhInnit = function( ) {
            $http.get("/option/api/options/").then(function(res) {
            });
        }
    });
</script>
<div class="row " ng-controller="ttbhController" >
    <section class="col-md-12 mb-10" >
        <?php
        echo \Module\trungtambaohanh\Model\TrungTamBaoHanhForm::btnTrungTamBaoHanh("Trung Tâm Bảo Hành");
        echo \Module\trungtambaohanh\Model\PhuLucSuaChuaForm::btnPhuLucSuaChua("Phụ Lục Sửa Chữa");
        echo \Module\trungtambaohanh\Model\PhuLucSuaChuaForm::btnThem("Thêm Phụ Lục Sửa Chữa");
        ?>
        <a class="btn btn-primary" data-toggle="modal" href='#modal-id'>Import</a>
        <div class="modal fade" id="modal-id">
            <div class="modal-dialog ">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Import Data</h4>
                    </div>
                    <div class="modal-body no-padding " style="min-height: 300px;" >
                        <div role="tabpanel">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#Chonfile" aria-controls="Chonfile" role="tab" data-toggle="tab">Import Excell</a>
                                </li>
                                <li role="presentation">
                                    <a href="#Filemau" aria-controls="Filemau" role="tab" data-toggle="tab">File Mẫu</a>
                                </li>
                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="Chonfile">
                                    <div class="col-md-12">
                                        <form action="/trungtambaohanh/phulucsuachua/import/" enctype="multipart/form-data" method="POST" role="form">
                                            <p>chọn file *.xsl</p>
                                            <div class="form-group">
                                                <label for="">Chọn file</label>
                                                <input type="file" name="fileData" >
                                            </div>
                                            <button type="submit" class="btn btn-primary">Gửi</button>
                                        </form>
                                    </div>
                                </div>
                                <div role="tabpanel" class="tab-pane" id="Filemau">file mau</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="col-md-12 pb-10 mt-20" >
        <div class="connectedSortable" >
            <div class="box box-primary" >
                <div class="box-body table-responsive" >
                    <table class="table table-bordered dataTable " id="data" >
                        <thead>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Mã Phụ Lục</th>
                                <th>Tên Phụ Lục</th>
                                <th>Đơn Giá</th>
                                <th>Yêu Cầu</th>
                                <th>Linh Kiện</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($PhuLucSuaChuas as $index => $op) {
                                $_op = new \Module\trungtambaohanh\Model\PhuLucSuaChua($op);
                                ?>
                                <tr>
                                    <th>
                                        <?php
                                        echo Module\trungtambaohanh\Model\PhuLucSuaChuaForm::Sua($_op->Id);
                                        echo Module\trungtambaohanh\Model\PhuLucSuaChuaForm::Xoa($_op->Id);
                                        ?>

                                    </th>
                                    <th><?php echo $index + 1 ?></th>
                                    <th><?php echo $_op->Code ?></th>
                                    <th><?php echo $_op->Name ?></th>
                                    <th><?php echo $_op->DonGia ?></th>
                                    <th><?php echo $_op->YeuCau; ?></th>
                                    <th><?php echo $_op->LinhKien; ?></th>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Mã Phụ Lục</th>
                                <th>Tên Phụ Lục</th>
                                <th>Đơn Giá</th>
                                <th>Yêu Cầu</th>
                                <th>Linh Kiện</th>
                            </tr>
                        </tfoot>

                    </table>
                </div>
            </div>

        </div>
    </section>
</div>