<?php
$sanPham = new Module\sanpham\Model\SanPham();
$tong = 0;
$pagesIndex = isset($_GET["pagesIndex"]) ? intval($_GET["pagesIndex"]) : 1;
$pageNumber = isset($_GET["pageNumber"]) ? intval($_GET["pageNumber"]) : 10;
$DanhMuc = isset($_GET["dm"]) ? $_GET["dm"] : 0;
$keyword = isset($_GET["keyword"]) ? $_GET["keyword"] : "";
$name["danhmuc"] = $DanhMuc;
$name["keyword"] = $keyword;
$SanPhams = $sanPham->SanPhamsPT($name, $pagesIndex, $pageNumber, $tong);
$totalPage = ceil($tong / $pageNumber);
?>
<ol class="breadcrumb" >
    <li>Sách Sản Phẩm</li>
</ol>
<form action="" enctype="multipart/form-data" method="POST" >
    <div class=" ">
        <div class="container-fluid" >
            <div class="box box-primary" >
                <div class="box-header" >
                    <h3 class="box-title" >Danh Sách Sản Phẩm (<?php echo $tong; ?>)</h3>
                    <div class="box-tools">
                        <a  class="btn btn-primary" data-toggle="modal" href='#XemTrenDiDong'>
                            <i class="fa fa-qrcode" ></i>
                        </a>
                        <div class="modal fade" id="XemTrenDiDong">
                            <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title">Xem Trên Di Động</h4>
                                    </div>
                                    <div class="modal-body">
                                        <img src="<?php echo \Common\Common::LinkQrcode(\Common\Common::Actual_link()); ?>" class="img img-responsive" alt="alt" title="alt" >
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button type="button" data-target="#TimKiem" class="btn-toggle btn btn-primary" ><i class="fa fa-search" ></i></button>
                        <button onclick="window.location.reload();" data-toggle="tooltip" data-placement="top" title="Reload" type="button" class="btn btn-default" ><i class="fa fa-refresh" ></i></button>
                    </div>
                </div>
                <div class="box-body " >
                    <div class="row">
                        <div class="col-md-12 " style="display: none;" id="TimKiem" >
                            <div class="row">
                                <div class="col-md-2" >
                                    <?php
                                    Model\FormOptions::TimKiem($keyword, ["id" => "TuKhoa", "onchange" => "TimKiemSanPham()"])->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-2" >
                                    <?php
                                    Module\sanpham\Model\SanPhamForm::DanhMuc($DanhMuc, ["id" => "DanhMucSanPham", "onchange" => "TimKiemSanPham()"])->renderHTML();
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="row">
                            <div class="table-responsive">
                                <table class="table table-hover table-bordered " id="data"   >
                                    <thead>
                                        <tr class="bg-blue" >
                                            <th  style="width: 100px;" ></th>
                                            <th style="width: 50px;" >STT</th>
                                            <th style="width: 100px;" >Mã </th>
                                            <th  >Tên Sản Phẩm</th>
                                            <th style="width: 240px;" >Danh Mục</th>
                                            <th style="width: 160px;" >Tình Trạng</th>
                                            <th style="width: 150px;" >Tên Đại Lý</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        foreach ($SanPhams as $k => $sp) {
                                            $_sp = new Module\sanpham\Model\SanPham($sp);
                                            ?>
                                            <tr class="" >
                                                <th class="text-center" >
                                                    <a href="/sanpham/taosanpham/edit/<?php echo $_sp->Id(); ?>/" data-toggle="tooltip" data-placement="top" title="Chi Tiết" class="  btn btn-xs btn-success" >
                                                        <i class="fa fa-eye"  ></i>
                                                    </a>
                                                    <a  class="btn btn-xs btn-primary" data-toggle="modal" href='#modal<?php echo $_sp->Id(); ?>'>
                                                        <i class="fa fa-qrcode" ></i>
                                                    </a>
                                                    <div class="modal fade" id="modal<?php echo $_sp->Id(); ?>">
                                                        <div class="modal-dialog modal-sm">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                                    <h4 class="modal-title">QR code</h4>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <img src="<?php echo $_sp->LinkQRcodeBaoHanh(); ?>" class="img img-responsive" alt="alt" title="alt" >
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </th>
                                                <th class="text-center" ><?php echo ($pagesIndex - 1) * $pageNumber + $k + 1; ?></th>
                                                <th><?php echo $_sp->TemBaoHang()->Code; ?></th>
                                                <th><?php echo $_sp->Name ?></th>
                                                <th>
                                                    <?php
                                                    echo $_sp->DanhMuc()->Name;
                                                    ?>
                                                </th>
                                                <th><?php echo $_sp->TinhTrang(); ?></th>
                                                <th><?php echo $_sp->DaiLy()->Name; ?></th>
                                            </tr>
                                            <?php
                                        }
                                        ?>
                                    </tbody>
                                    <tfoot>
                                        <tr >
                                            <th colspan="7" >
                                                <div class="col-xs-2 col-md-1 " style="margin-top: 20px" >
                                                    <?php
                                                    Model\FormOptions::HienThu($pageNumber, ["id" => "HienThi", "onchange" => "TimKiemSanPham()"])->render();
                                                    ?>
                                                </div>
                                                <div class="col-xs-10 col-md-11 "   >
                                                    <?php
                                                    $linkPt = "/sanpham/kho/index/?pagesIndex=[i]&dm={$DanhMuc}&pageNumber={$pageNumber}";
                                                    echo Common\Common::PhanTrang($totalPage, $pagesIndex, $linkPt);
                                                    ?>
                                                </div>
                                            </th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <table class="table table-bordered" >

                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>
<script type="text/javascript" >
    function TimKiemSanPham() {
        var path = "/sanpham/kho/index/?pagesIndex=1&pageNumber=[pn]&dm=[dm]&keyword=[key]";
        var DM = $("#DanhMucSanPham").val();
        var tukhoa = $("#TuKhoa").val();
        var hienThi = $("#HienThi").val();
        path = path.replace('[pn]', hienThi);
        path = path.replace('[dm]', DM);
        path = path.replace('[key]', tukhoa);
        window.location.href = path;
    }
</script>