<script type="text/javascript" >
    app.controller("projectcontrollerController", function($scope, $http) {
        $scope.projectcontrollerInnit = function(id) {
            $http.get("/project/api/controllersdata/").then(function(res) {
                $scope._Project = res.data;
            });
        }
    });
</script>

<!-- End Facebook Pixel Code -->
<div class="row " ng-controller="projectcontrollerController" ng-init="projectcontrollerInnit('<?php echo $_Param[0] ?>')" >
    <section class="col-md-12 pb-10" >
        <div class="connectedSortable" >
            <a href="/project/controller/index/<?php echo $project->PId; ?>" class="btn btn-primary" ><i class="fa fa-arrow-left" ></i></a>
            <a href="/project/controller/datacontroller2excell/" class="btn btn-primary" >Export Excell</a>
<!--            <a href="mailTo:<?php echo Module\project\Model\Project::GetCurentProject(TRUE)->Email; ?>" class="btn btn-primary" >Gửi Mail</a>-->
            <div class="box box-primary" >
                <div class="box-header" >
                    <h3 class="box-title" >Danh Sách Người Dùng</h3>
                </div>
                <div class="box-body table-responsive" >
                    <table data-column="[7]" data-btn=".btn-groups" class="table table-bordered dataTableAjaxServer" id="datatable001" data-ajax="/project/api/controllersdataajaxPt/" >
                        <thead>
                            <tr>

                                <th>#</th>
                                <th>Email</th>
                                <th>Họ & Tên</th>
                                <th>Nguồn</th>
                                <th>Ngày Đăng Nhập</th>
                                <th>Số Lần Đăng Nhập</th>
                                <th></th>

                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Email</th>
                                <th>Họ & Tên</th>
                                <th>Nguồn</th>
                                <th>Ngày Đăng Nhập</th>
                                <th>Số Lần Đăng Nhập</th>
                                <th></th>
                            </tr>
                        </tfoot>

                    </table>
                </div>
            </div>

        </div>
    </section>
</div>
<!--<script>
    $(function() {
        $(".datatable").DataTable();

    });
</script>-->