<?php
$IdProject = \Module\project\Model\Project::GetCurentProject(true)->Id;
?>

<script type="text/javascript" >
    app.controller("projectcontrollerController", function($scope, $http) {
        $scope.projectcontrollerInnit = function(id) {
            $http.get("/project/api/controller/").then(function(res) {
                $scope._Project = res.data;
            });
        }
    });
</script>
<div class="row " ng-controller="projectcontrollerController" ng-init="projectcontrollerInnit('<?php echo $_Param[0] ?>')" >
    <section class="col-md-12 pb-10" >
        <div class="connectedSortable" >
            <a class="btn btn-primary" data-toggle="modal" href='#ThemOptions'>Thêm</a>
            <form method="POST" action="/project/controller/create/" enctype="multipart/form-data" >
                <div class="modal fade" data-backdrop="false"  id="ThemOptions">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">Thêm Controller</h4>
                            </div>
                            <div class="modal-body">
                                <?php
                                \Module\project\Model\ControllerForm::Name()->renderHTML();
                                \Module\project\Model\ControllerForm::Lat()->renderHTML();
                                \Module\project\Model\ControllerForm::Lon()->renderHTML();
                                \Module\project\Model\ControllerForm::Ip()->renderHTML();
                                \Module\project\Model\ControllerForm::Username()->renderHTML();
                                \Module\project\Model\ControllerForm::Password()->renderHTML();
                                ?>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                                <button type="submit" name="btnsave" class="btn btn-primary">Thêm</button>
                            </div>
                        </div>
                    </div>
                </div>

            </form>

            <div class="box box-primary" >
                <div class="box-header" >
                    <h3 class="box-title" >Controller</h3>
                </div>
                <div class="box-body table-responsive" >
                    <table class="table table-bordered" >
                        <thead>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Name Controller</th>
                                <th>Lat/Long</th>
                                <th>IP</th>
                                <th>Username</th>
                                <th>Password</th>

                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="item in _Project" >
                                <td>
                                    <a href="/project/controller/edit/{{item.token}}" class="btn btn-success" >
                                        <i class="fa fa-edit" ></i>
                                    </a>
                                    <a target="_blank" href="{{item.LinkLogin}}" class="btn btn-success" >
                                        <i class="fa fa-sign-in" ></i>
                                    </a>
                                </td>
                                <td>{{$index + 1}}</td>
                                <td><a href="/project/controller/datacontroller/{{item.token}}">{{item.Name}}</a></td>
                                <td><i class="fa fa-map-marker" ></i>{{item.Lat}}.{{item.Lon}}</td>
                                <td>{{item.Ip}}</td>
                                <td>{{item.Username}}</td>
                                <td><input value="{{item.Password}}" type="password" ></td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Name</th>
                                <th>Lat/Long</th>
                                <th>IP</th>
                                <th>Username</th>
                                <th>Password</th>
                            </tr>
                        </tfoot>

                    </table>
                </div>
            </div>

        </div>
    </section>
</div>