<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bảo Hành</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
        integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="/public/tmd/style.css" crossorigin="anonymous">
    <link href="/public/theme/TMD/css/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <script src="/public/root/assets/libs/angular.min.js" type="text/javascript"></script>
    <style>
        .textareaHeight {
            height: 106px !important;
        }
    </style>
    <script src="/public/tmd/App.js?v=<?php echo time() ?>" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="/public/admin/plugins/jQuery/jquery-3.5.1.js"></script>

</head>

<body ng-app="RootApp">
    <div class="">
        <?php
        include $_Content;
        ?>
    </div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
        integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
        crossorigin="anonymous"></script>
</body>

</html>