<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>QuyetMa</title>
        <link href="/public/theme/TMD/css/bootstrap-4.3.1.css" rel="stylesheet">
        <link rel="stylesheet" href="/public/theme/TMD/css/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="/public/theme/TMD/plugin/OwlCarousel/assets/owl.carousel.css">
        <link href="/public/theme/TMD/css/style.css" rel="stylesheet" type="text/css">
        <script src="/public/theme/TMD/js/jquery-3.3.1.min.js"></script>
        <script src="/public/instascan.min.js" type="text/javascript"></script>

    </head>
    <body>
        <?php
        include $_Content;
        ?>
        <script type="text/javascript" src="/public/theme/TMD/plugin/OwlCarousel/owl.carousel.min.js"></script>
        <script src="/public/theme/TMD/js/popper.min.js"></script>
        <script src="/public/theme/TMD/js/bootstrap-4.3.1.js"></script>
        <script src="/public/theme/TMD/js/seting.js"></script>
    </body>
</html>
