<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Trung Tâm Chăm Sóc Khách Hàng</title>
        <!-- Bootstrap -->
        <link href="/public/theme/TMD/css/bootstrap-4.3.1.css" rel="stylesheet">
        <link rel="stylesheet" href="/public/theme/TMD/css/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="/public/theme/TMD/plugin/OwlCarousel/assets/owl.carousel.css">
        <link href="/public/theme/TMD/css/style.css" rel="stylesheet" type="text/css">
        <script src="/public/theme/TMD/js/jquery-3.3.1.min.js"></script>
        <script src="/public/instascan.min.js" type="text/javascript"></script>

    </head>
    <body>
        <header>
            <div class="menu-top affix" data-top="80" data-class="bg-menu" >
                <div class="container  ">
                    <div class="row ">
                        <div class="col-md-4 ">
                            <a href="/">
                                <img src="/public/theme/TMD/images/logo.png" alt="webname" class="logo-img">
                            </a>
                        </div>
                        <div class="col-md-8 ">
                            <div class="row">
                                <nav class="Main-menu navbar navbar-expand-sm mt-2" style="width: 100%;"> <a class="navbar-brand d-md-none" href="#">Menu</a>
                                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1" aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"> <i class="fa fa-list-ul" ></i> </span> </button>
                                    <div class="collapse  main-menu navbar-collapse" id="navbarSupportedContent1">
                                        <ul class="navbar-nav ">
                                            <li class="nav-item"> <a class="nav-link" href="#">Trang Chủ</a></li>
                                            <li class="nav-item"> <a class="nav-link" href="#">Giới Thiệu</a> </li>
                                            <li class="nav-item"> <a class="nav-link" href="#">Bảo Hành</a></li>
                                            <li class="nav-item"> <a class="nav-link" href="#">Liên Hệ</a></li>
                                            <li class="nav-item"> <a class="nav-link" href="http://thanhminhduc.com/">Thành Minh Đức</a> </li>
                                            <li class="nav-item"> <a class="nav-link" href="/user/login/index">Nhân Viên</a> </li>
                                        </ul>
                                    </div>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <?php
        include $_Content;
        ?>
        <footer class="footer pt-4">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <iframe class="footer-map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7837.021918893618!2d106.6544982456575!3d10.848687590678784!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317529bf1b84a1fd%3A0xe9b1c81106026fc9!2zVHLGsOG7nW5nIHRp4buDdSBo4buNYyBMw6ogVsSDbiBUaOG7jQ!5e0!3m2!1svi!2sus!4v1601992773262!5m2!1svi!2sus"  frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                    </div>
                    <div class="col-md-4">
                        <h4 class="footer-title"> Liên Hệ </h4>
                        <address class="text-left ">
                            <strong> Trụ sở :</strong> 323/6 Lê Văn Thọ, Phường 9, Quận Gò Vấp, TP. Hồ Chí Minh <br>
                            <strong> Chi nhánh số 1: </strong>386/26 Bùi Trọng Nghĩa, Khu phố 3, Phường Trảng Dài, Tp. Biên Hòa, Tỉnh Đồng Nai <br>
                            <strong> Nhà riêng: </strong>44 Bùi Trọng Nghĩa, KP.3, P.Trảng Dài, Tp. Biên Hòa, Đồng Nai. <br>
                            Email: <strong>Sakimmai@gmail.com</strong> <br>
                            Skype: <strong>sakimmai@gmail.com</strong>
                        </address>
                    </div>
                    <div class="col-md-4">
                        <h4 class="text-left footer-title">Nhận Tin Mới Nhất </h4>
                        <p class="title-mail">Đăng ký bản tin của chúng tôi và cập nhật những tin tức và giao dịch mới nhất! </p>
                        <div class=" my-1">
                            <label class="sr-only" for="inlineFormInputGroupUsername">Email</label>
                            <div class="input-group">
                                <input type="text" class="form-control" id="inlineFormInputGroupUsername" placeholder="Email">
                                <div class="input-group-prepend">
                                    <button class="btn-waning input-group-text btn-theme">Gửi</button>
                                </div>
                            </div>
                        </div>
                        <div class="text-center" >
                            <div class="btn-group mt-3"  role="group">
                                <button type="button" class="btn btn-secondary"><i class="fa fa-facebook" ></i></button>
                                <button type="button" class="btn btn-secondary"><i class="fa fa-google" ></i></button>
                                <button type="button" class="btn btn-secondary"><i class="fa fa-twitter" ></i></button>
                                <button type="button" class="btn btn-secondary"><i class="fa fa-rss" ></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

        <script type="text/javascript" src="/public/theme/TMD/plugin/OwlCarousel/owl.carousel.min.js"></script>
        <script src="/public/theme/TMD/js/popper.min.js"></script>
        <script src="/public/theme/TMD/js/bootstrap-4.3.1.js"></script>
        <script src="/public/theme/TMD/js/seting.js"></script>
    </body>
</html>
