<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap - Prebuilt Layout</title>
        <!-- Bootstrap -->
        <link href="/public/theme/TMD/css/bootstrap-4.3.1.css" rel="stylesheet">
        <link rel="stylesheet" href="/public/theme/TMD/css/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="/public/theme/TMD/plugin/OwlCarousel/assets/owl.carousel.css">
        <link href="/public/theme/TMD/css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <header>
            <div class="fixed-top menu-top affix" data-top="80" data-class="bg-menu" >
                <div class="container  ">
                    <div class="row ">
                        <div class="col-md-4 ">
                            <a href="/">
                                <img src="/public/theme/TMD/images/logo.png" alt="webname" class="logo-img">
                            </a>
                        </div>
                        <div class="col-md-8 ">
                            <div class="row">
                                <nav class="Main-menu navbar navbar-expand-sm mt-2" style="width: 100%;"> <a class="navbar-brand d-md-none" href="#">Menu</a>
                                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1" aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"> <i class="fa fa-list-ul" ></i> </span> </button>
                                    <div class="collapse  main-menu navbar-collapse" id="navbarSupportedContent1">
                                        <ul class="navbar-nav ">
                                            <li class="nav-item"> <a class="nav-link" href="#">Trang Chủ</a></li>
                                            <li class="nav-item"> <a class="nav-link" href="#">Giới Thiệu</a> </li>
                                            <li class="nav-item"> <a class="nav-link" href="#">Bảo Hành</a></li>
                                            <li class="nav-item"> <a class="nav-link" href="#">Liên Hệ</a></li>
                                            <li class="nav-item"> <a class="nav-link" href="http://thanhminhduc.com/">Thành Minh Đức</a> </li>
                                        </ul>
                                    </div>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <section class="mainslide">
            <div id="carouselExampleIndicators1" class="carousel slide" data-ride="carousel"  >
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active" style="background-image: url('/public/theme/TMD/images/banner.jpg')"  > </div>
                    <div class="carousel-item" style="background-image: url('/public/theme/TMD/images/banner.jpg')"> </div>
                    <div class="carousel-item" style="background-image: url('/public/theme/TMD/images/banner.jpg')"> </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators1" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a> <a class="carousel-control-next" href="#carouselExampleIndicators1" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a> </div>
            <div class="danhSachDoiTac bg-dark60 p-2 " >
                <div class="container " >
                    <div class="owl-custom DanhSachDoiTac owl-carousel owl-theme" data-responsive='{"380":{"items":2},"600":{"items":4},"1000":{"items":8}}'  data-dots-each="true" data-dots="false" data-loop="true" data-nav="true" data-margin="10" >
                        <div class="item "> <a href="#"> <img class="" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
                        <div class="item "> <a href="#"> <img class="" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
                        <div class="item "> <a href="#"> <img class="" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
                        <div class="item "> <a href="#"> <img class="" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
                        <div class="item "> <a href="#"> <img class="" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="Content mt-4">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-justify">
                    </div>
                </div>
            </div>
        </section>
        <section class="">
            <div class=" ">
                <div class=" ">
                    <div>
                        <div class="bg-theme taisaochonchungtoi p-3">
                            <div class="container">
                                <div class="row p-4">
                                    <div class="col-md-8  ">
                                        <h2 class="text-center">Gọi Cho Chúng Tôi Để Được Tư Vấn</h2>
                                    </div>
                                    <div class="col-md-4 ">
                                        <h2 class="">
                                            <i class="fa fa-phone " ></i> 0123456789
                                        </h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <section class="BaiVietNoiBat bg-gray p-3 pt-4" >
            <div class="container">
                <div class="row ">
                    <div class="col-md-12">
                        <h2 class="text-center fw-bold fs-3 p-3" >Dịch Vụ</h2>
                    </div>
                    <div class="col-md-6">
                        <div class="card border-radius-0 BaiVietNoiBat-Main "> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap">
                            <div class="card-body">
                                <h5 class="card-title">Card title</h5>
                                <hr style="border-bottom: 1px solid #fff;"  >
                                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content. </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-12 mb-4">
                                <div class="card border-radius-0 BaiVietNoiBat2"> <img  class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap">
                                    <div class="">
                                        <h5 class="card-title">Card title</h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="card border-radius-0 BaiVietNoiBat3"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap">
                                    <div class="">
                                        <h5 class="card-title">Card title</h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="card border-radius-0 BaiVietNoiBat3"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap">
                                    <div class="">
                                        <h5 class="card-title">Card title</h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="card border-radius-0 BaiVietNoiBat3"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap">
                                    <div class=" ">
                                        <h5 class="card-title">Card title</h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="card border-radius-0 BaiVietNoiBat3"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap">
                                    <div class=" ">
                                        <h5 class="card-title">Card title</h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="" >
            <div class=" ">
                <div class=" ">
                    <div>
                        <div class="bg-theme taisaochonchungtoi p-3">
                            <h2 class="title taisaochonchungtoi-title text-center">Tại sao chọn chúng tôi?</h2>
                            <hr>
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="row">
                                            <div class="col-md-4 item">
                                                <h2 class="mb-0 text-center" >Chuyên Nghiệp</h2>
                                                <p class="text-center" >Chuyên nghiệp trong tư vấn, làm hồ sơ </p>
                                            </div>
                                            <div class="col-md-4 item">
                                                <h2 class="mb-0 text-center" >Chính Xác</h2>
                                                <p class="text-center" >Chúng tôi cam kết làm việc chính xác đến từng chi tiết </p>
                                            </div>
                                            <div class="col-md-4 item">
                                                <h2 class="mb-0 text-center" >Hiệu Quả</h2>
                                                <p class="text-center" >Làm việc hiệu quả cho từng chi phí của khách hàng </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="ChungToiLaAi bg-gray p-3 pt-4" >
            <div class="container">
                <div class="row ">
                    <div class="col-md-12">
                        <h2 class="text-center fw-bold fs-3 p-3" >Chúng Tôi Là Ai?</h2>
                    </div>
                    <div class="col-md-4">
                        <div class="card border-radius-0   ">
                            <h2 class="card-title text-center fs-4 pt-5">Card title</h2>
                            <div class="card-body text-justify">
                                <hr style="border-bottom: 1px solid #fff;"  >
                                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content. </p>
                            </div>
                            <a href="#" class="btn bnt-primary">Xem Thêm <i class="fa fa-angle-double-right"  ></i></a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card border-radius-0   ">
                            <h2 class="card-title text-center fs-4 pt-5">Card title</h2>
                            <div class="card-body text-justify">
                                <hr style="border-bottom: 1px solid #fff;"  >
                                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content. </p>
                            </div>
                            <a href="#" class="btn bnt-primary">Xem Thêm <i class="fa fa-angle-double-right"  ></i></a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card border-radius-0   ">
                            <h2 class="card-title text-center fs-4 pt-5">Card title</h2>
                            <div class="card-body text-justify">
                                <hr style="border-bottom: 1px solid #fff;"  >
                                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content. </p>
                            </div>
                            <a href="#" class="btn bnt-primary">Xem Thêm <i class="fa fa-angle-double-right"  ></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="bg-dark" >
            <div class="container">
                <h2 class="p-3 fs-3 text-center color-while" >Khách Hàng Nói Về Chúng Tôi</h2>
                <div id="carouselExampleIndicators2" class="NhanXetCuaKhacHang carousel slide" data-ride="carousel"  >
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <div class="carousel-caption">
                                <h5> Third slide Heading</h5>
                                <p>
                                <blockquote>Third slide Caption</blockquote>
                                </p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="carousel-caption">
                                <h5> Third slide Heading</h5>
                                <p>
                                <blockquote>Third slide Caption</blockquote>
                                </p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="carousel-caption">
                                <h5> Third slide Heading</h5>
                                <p>
                                <blockquote>Third slide Caption</blockquote>
                                </p>
                            </div>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators2" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a> <a class="carousel-control-next" href="#carouselExampleIndicators2" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a> </div>
            </div>
        </section>
        <section>
            <div class="container p-4" >
                <div class="owl-custom DanhSachDoiTac owl-carousel owl-theme" data-responsive='{"380":{"items":2},"600":{"items":4},"1000":{"items":6}}'  data-dots-each="true" data-dots="false" data-loop="true" data-nav="true" data-margin="10" >
                    <div class="card item "> <a href="#"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
                    <div class="card item "> <a href="#"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
                    <div class="card item "> <a href="#"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
                    <div class="card item "> <a href="#"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
                    <div class="card item "> <a href="#"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
                </div>
            </div>
        </section>
        <footer class="footer pt-4">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <iframe class="footer-map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7837.021918893618!2d106.6544982456575!3d10.848687590678784!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317529bf1b84a1fd%3A0xe9b1c81106026fc9!2zVHLGsOG7nW5nIHRp4buDdSBo4buNYyBMw6ogVsSDbiBUaOG7jQ!5e0!3m2!1svi!2sus!4v1601992773262!5m2!1svi!2sus"  frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                    </div>
                    <div class="col-md-4">
                        <h4 class="footer-title"> Liên Hệ </h4>
                        <address class="text-left ">
                            <strong> Trụ sở :</strong> 323/6 Lê Văn Thọ, Phường 9, Quận Gò Vấp, TP. Hồ Chí Minh <br>
                            <strong> Chi nhánh số 1: </strong>386/26 Bùi Trọng Nghĩa, Khu phố 3, Phường Trảng Dài, Tp. Biên Hòa, Tỉnh Đồng Nai <br>
                            <strong> Nhà riêng: </strong>44 Bùi Trọng Nghĩa, KP.3, P.Trảng Dài, Tp. Biên Hòa, Đồng Nai. <br>
                            Email: <strong>Sakimmai@gmail.com</strong> <br>
                            Skype: <strong>sakimmai@gmail.com</strong>
                        </address>
                    </div>
                    <div class="col-md-4">
                        <h4 class="text-left footer-title">Nhận Tin Mới Nhất </h4>
                        <p class="title-mail">Đăng ký bản tin của chúng tôi và cập nhật những tin tức và giao dịch mới nhất! </p>
                        <div class=" my-1">
                            <label class="sr-only" for="inlineFormInputGroupUsername">Email</label>
                            <div class="input-group">
                                <input type="text" class="form-control" id="inlineFormInputGroupUsername" placeholder="Email">
                                <div class="input-group-prepend">
                                    <button class="btn-waning input-group-text btn-theme">Gửi</button>
                                </div>
                            </div>
                        </div>
                        <div class="text-center" >
                            <div class="btn-group mt-3"  role="group">
                                <button type="button" class="btn btn-secondary"><i class="fa fa-facebook" ></i></button>
                                <button type="button" class="btn btn-secondary"><i class="fa fa-google" ></i></button>
                                <button type="button" class="btn btn-secondary"><i class="fa fa-twitter" ></i></button>
                                <button type="button" class="btn btn-secondary"><i class="fa fa-rss" ></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <div class="hotline"> <a href="tel:19001017"><img src="/public/theme/TMD/images/hotline.png" height="70" alt="hotline"/></a> </div>
        <script src="/public/theme/TMD/js/jquery-3.3.1.min.js"></script>
        <script type="text/javascript" src="/public/theme/TMD/plugin/OwlCarousel/owl.carousel.min.js"></script>
        <script src="/public/theme/TMD/js/popper.min.js"></script>
        <script src="/public/theme/TMD/js/bootstrap-4.3.1.js"></script>
        <script src="/public/theme/TMD/js/seting.js"></script>
    </body>
</html>
