<form method="POST" action="/option/index/create/" enctype="multipart/form-data" >
    <div class="container">
        <div class=" panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">panel-title</h3>
            </div>
            <div class="panel-body">
                <?php
                \Module\option\Model\OptionForm::Code()->renderHTML();
                \Module\option\Model\OptionForm::Name()->renderHTML();
                \Module\option\Model\OptionForm::Groups()->renderHTML();
                \Module\option\Model\OptionForm::Note()->renderHTML();
                \Module\option\Model\OptionForm::Parents(0)->renderHTML();
                \Module\option\Model\OptionForm::OrderBy(0)->renderHTML();
                ?>
            </div>
            <div class="panel-footer" >
                <button type="submit" name="btnsave" class="btn btn-primary">Thêm</button>
            </div>
        </div>

    </div>
</form>