<div class="container" >
    <div class="panel panel-primary">
        <div ng-show="alert.isShow" class="alert alert-{{alert.type}}" role="alert">
            {{alert.contentMess}}
        </div>
        <div class="panel-heading">
            <h3 class="panel-title">Yêu cầu bảo hành</h3>
        </div>
        <div class="panel-body">
            <div class="form-xuly-yeucau-baohanh"  formdata-defaut="_Yeucaubaohanh" ></div>
            <!--<form-yeu-cau-bao-hanh formdata-defaut="_Yeucaubaohanh" ></form-yeu-cau-bao-hanh>-->
        </div>
    </div>
</div>
