<?php
use Module\trungtambaohanh\Model\YeuCauBaoHanh;

$ycbh = new YeuCauBaoHanh($_Param[0]);
?>
<ol class="breadcrumb hidden-sm hidden-xs">
    <li>
        <a href="/trungtambaohanh/yeucaubaohanh/index/<?php echo $ycbh->Code; ?>">
            Chi Tiết Yêu Cầu
        </a>
    </li>
    <li class="active">Kiểm tra tem </li>
</ol>
<script src="/Module/dashboard/public/html5-qrcode.min.js" type="text/javascript"></script>
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 mt-20">
            <a href="/dashboard/index/index/" class="btn hidden-lg hidden-md btn-primary" >
                <i class="fa fa-arrow-left" ></i>
                <span class="hidden-sm hidden-xs" >
                    Quay lại
                </span>
            </a>
            <h3 class="text-center">Quét tem sản phẩm</h3>
            <p class="text-red" >Nhân viên bảo hành quét tem để bắt đầu bảo hành</p>
            <div id="qr-reader" style=" width:auto;margin: auto;"></div>
            <div class="thongbao bg-green" id="alertCode"></div>
            <div id="error"></div>
            <div id="countResults"></div> 
            <textarea style="display: none;width: 100%;height: 30px;" id="qr-reader-results"></textarea>
        </div>
    </div>
</div>
<script>
    class NhapMa {
        content;
        idElement;
        code;
        constructor(content) {
            this.content = content
        }
        GetCodeByQrcode() {

            var res = this.content.split("/");
            // alert(this.content);
            // alert(res[3]);
            return res[3];
        }
        GetUrl() {
            this.code = this.GetCodeByQrcode();
            var CodeTem = this.code;
            var link = `/trungtambaohanh/yeucaubaohanh/TenBaoHanh/${CodeTem}/`;
            window.location.href =link;
            // $.ajax({
            //     type: "get",
            //     url: `/trungtambaohanh/api/SanPhamTheoMaTem/${CodeTem}/`,
            //     dataType: "html",
            //     success: function (response) {
            //         $("#ThongTinSanPham").html(response);
            //     }
            // });
        }

    }

    function docReady(fn) {
        // see if DOM is already available
        if (document.readyState === "complete"
            || document.readyState === "interactive") {
            // call on next available tick
            setTimeout(fn, 100);
        } else {
            document.addEventListener("DOMContentLoaded", fn);
        }
    }
    docReady(function () {
        try {
            var resultContainer = document.getElementById('qr-reader-results');
            var lastResult, countResults = 0;
            function onScanSuccess(decodedText, decodedResult) {
                if (decodedText !== lastResult) {
                    ++countResults;
                    lastResult = decodedText;
                    // Handle on success condition with the decoded message.
                    resultContainer.innerHTML = `${decodedText}`;
                    var nhapMa = new NhapMa(decodedText);
                    nhapMa.GetUrl();
                    // countResultsHtml = document.getElementById("countResults");
                    // countResultsHtml.innerHTML = "Số Lần Quét: " + countResults;
                }
            }
            var html5QrcodeScanner = new Html5QrcodeScanner(
                "qr-reader", { fps: 10, qrbox: 250 });
            html5QrcodeScanner.render(onScanSuccess);
        } catch (error) {
            var errorHtml = document.getElementById("error");
            errorHtml.innerHTML += error;
        }
    });
</script>