<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>[Website]</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.5 -->
        <link rel="stylesheet" href="/public/admin/bootstrap/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="/public/admin/dist/css/AdminLTE.min.css">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
             folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="/public/admin/dist/css/skins/_all-skins.min.css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <script src="/public/root/assets/assetConfig.js"></script>
        <link href="/public/admin/dist/Custom.css" rel="stylesheet" type="text/css"/>
        <script type="text/javascript" >
            var app = angular.module("rootApp", ["ngRoute"]);
        </script>
    </head>
    <body class="skin-blue-light sidebar-mini "  ng-cloak="TRUE" ng-app="rootApp" >
        <div class="wrapper">
            <?php
            Module\user\Views\Layout\flayout::Menu();
            ?>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <?php
                $a = \Common\Alert::getAlert();
                if ($a) {
                    ?>
                    <div class="alert alert-<?php echo $a["Type"] ?>" ><?php echo $a["Content"] ?></div>
                    <?php
                }
                ?>
                <?php include $_Content; ?>
            </div><!-- /.content-wrapper -->
            <footer class="main-footer hidden">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 2.3.0
                </div>
                <strong>Copyright &copy; 2014-2015 <a href="">Almsaeed Studio</a>.</strong> All rights reserved.
            </footer>

        </div><!-- ./wrapper -->

        <!-- jQuery 2.1.4 -->
        <script src="/public/admin/plugins/jQuery/jQuery-2.1.4.min.js"></script>
        <!-- Bootstrap 3.3.5 -->
        <script src="/public/admin/bootstrap/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="/public/admin/plugins/fastclick/fastclick.min.js"></script>
        <!-- AdminLTE App -->
        <script src="/public/admin/dist/js/app.min.js"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="/public/admin/dist/js/demo.js"></script>
    </body>
</html>

<?php
\Common\Common::DeCodeHTML();
?>