<?php
if (isset($_POST["OnSave"])) {
    try {
        $DanhMuc = $_POST["DanhMuc"];
        $DM = new Module\sanpham\Model\DanhMucSanPham();
        $DM->Post($DanhMuc);
        Common\Common::toUrl("/sanpham/index/");
    } catch (Exception $exc) {
        $ThongBao = $exc->getMessage();
    }
}
$option = new \Module\option\Model\Option();
?>
<ol class="breadcrumb" >
    <li><a href="/sanpham/index/" >Danh Mục Sản Phẩm</a></li>
    <li>Thêm </li>
</ol>
<div class="container" >
    <div class="row " ng-controller="rmmController" ng-init="rmmInnit()" >
        <section class="col-md-12 pb-10" >
            <form action="" method="POST" enctype="multipart/form-data" >
                <div class="connectedSortable" >
                    <div class="box box-solid">
                        <div class=" box-header bg-blue-gradient">
                            <h3 class="box-title">Thêm</h3>
                            <!-- tools box -->
                        </div>
                        <div class="box-body">
                            <p><?php echo (!empty($ThongBao)) ? $ThongBao : "" ?></p>
                            <?php
                            \Module\sanpham\Model\DanhMucSanPhamForm::Code($option->Code)->renderHTML();
                            \Module\sanpham\Model\DanhMucSanPhamForm::Name($option->Name)->renderHTML();
                            \Module\sanpham\Model\DanhMucSanPhamForm::Groups($option->Groups)->render();
                            \Module\sanpham\Model\DanhMucSanPhamForm::Note($option->Note)->renderHTML();
                            \Module\sanpham\Model\DanhMucSanPhamForm::Parents($option->Parents)->renderHTML();
                            \Module\sanpham\Model\DanhMucSanPhamForm::OrderBy(1)->renderHTML();
                            ?>
                        </div>
                        <div class="box-footer" >
                            <?php
                            \Module\sanpham\Model\DanhMucSanPhamForm::btnSubmit()->render();
                            ?>
                        </div>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>
