<?php
$Options = Module\option\Model\Option::OptionByGroups(Module\option\Model\Option::DanhMucVatTu);
?>
<div class="row " >
    <section class="col-md-12 mb-10" >
        <a class="btn btn-primary" href='/sanpham/taosanpham/'>Tạo Sản Phẩm</a>
    </section>
    <section class="col-md-12 pb-10 mt-20" >
        <div class="connectedSortable" >
            <div class="box box-primary" >
                <div class="box-body table-responsive" >
                    <table class="table table-bordered dataTable " id="data"   >
                        <thead>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Mã Danh Mục</th>
                                <th>Tên Danh Mục</th>
                                <th>Chung Loại</th>
                                <th>Ghi Chú</th>
                                <th>Xắp Sếp</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($Options as $k => $op) {
                                $_op = new Module\option\Model\Option($op);
                                ?>
                                <tr>
                                    <td>
                                        <a href="/sanpham/index/edit/<?php echo $_op->Id ?>/" class="btn btn-primary" >Sửa</a>
                                        <a href="/sanpham/index/delete/" data-confirm="Xóa Danh Mục Sản Phẩm" class="btn xoa btn-danger" >Xóa</a>
                                    </td>
                                    <td><?php echo $k + 1; ?></td>
                                    <td><?php echo $_op->Code ?></td>
                                    <td><?php echo $_op->Name ?></td>
                                    <td><?php echo $_op->Parents()->Name; ?></td>
                                    <td><?php echo $_op->Note ?></td>
                                    <td><?php echo $_op->OrderBy ?></td>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Mã Danh Mục</th>
                                <th>Tên Danh Mục</th>
                                <th>Chung Loại</th>
                                <th>Ghi Chú</th>
                                <th>Xắp Sếp</th>
                            </tr>
                        </tfoot>

                    </table>
                </div>
            </div>

        </div>
    </section>
</div>