<ol class="breadcrumb" >
    <li>Danh Mục Sản Phẩm</li>
</ol>
<?php
if (Common\Form::isPost()) {
    $DanhMuc = Common\Form::RequestPost("DanhMuc", []);

    foreach ($DanhMuc as $idSP => $value) {
        $DanhMuc = new Module\sanpham\Model\DanhMucSanPham();
        $ModelDanhMuc = $DanhMuc->GetById($idSP);
        $ModelDanhMuc["Parents"] = $value["Parent"];
        $DanhMuc->UpdateSubmit($ModelDanhMuc);
    }
}
$Options = Module\option\Model\Option::OptionByGroups(Module\option\Model\Option::DanhMucVatTu);
?>
<form action="" enctype="multipart/form-data" method="POST" >
    <div class="container-fluid" >
        <div class="box box-primary" >
            <div class="box-header" >
                <h3 class="box-title" >Danh Mục Sản Phẩm</h3>
                <div class="box-tools">
                    <a href="/sanpham/index/add" class="btn btn-primary" >Thêm Danh Mục</a>
                </div>
            </div>
            <div class="box-body " >
                <table class="table table-bordered dataTable " id="data"   >
                    <thead>
                        <tr class="bg-blue" >
                            <th></th>
                            <th>#</th>
                            <th>Mã Danh Mục</th>
                            <th>Tên Danh Mục</th>
                            <th>Chung Loại</th>
                            <th>Ghi Chú</th>
                            <th>Xắp Sếp</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($Options as $k => $op) {
                            $_op = new Module\option\Model\Option($op);
                            ?>
                            <tr>
                                <td>
                                    <a href="/sanpham/index/edit/<?php echo $_op->Id ?>/" class="btn btn-sm btn-primary" >Sửa</a>
                                    <a href="/sanpham/index/delete/<?php echo $_op->Id; ?>" data-confirm="Xóa Danh Mục Sản Phẩm" class="btn-sm btn xoa btn-danger" >Xóa</a>
                                </td>
                                <td><?php echo $k + 1; ?></td>
                                <td><?php echo $_op->Code ?></td>
                                <td><?php echo $_op->Name ?></td>
                                <td>
                                    <?php
                                    Module\sanpham\Model\DanhMucSanPhamForm::SelectGroupsID("", "DanhMuc[" . $_op->Id . "][Parent]", "ChungLoaiSP", $_op->Parents)->render();
                                    ?>
                                </td>
                                <td><?php echo $_op->Note ?></td>
                                <td><?php echo $_op->OrderBy ?></td>
                            </tr>
                            <?php
                        }
                        ?>
                    </tbody>
                </table>
                <button class="btn btn-success" name="SaveAll" >Cập Nhật</button>
            </div>
        </div>
    </div>
</form>