<ol class="breadcrumb">
    <li><a href="/dashboard/">Dashboard</a></li>
    <li><a href="/dashboard/xuatnhapkho/index" >Phiếu Xuất Nhập Kho</a></li>
    <li><a>Phiếu</a></li>
</ol>
<?php
use Model\FormOptions;
use Model\Obj2Html;
use Module\sanpham\Model\XuatNhapKho\PhieuXuatNhap;
use Module\sanpham\Model\XuatNhapKho\PhieuXuatNhapChiTiet;
use Module\user\Model\Admin; 

$admin = Admin::getCurentUser(true);
$CodeQr = new \Model\CodeQR($admin->Username);
$phieuXuatNhap = new PhieuXuatNhap($code);
$DSSanPham = $phieuXuatNhap->DanhSachSanPham();

?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Thông tin phiếu</h3>
                </div>
                <div class="box-body ">
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6 ">
                            <h3 class="text-center">
                                <?php echo $phieuXuatNhap->Name; ?>
                            </h3>
                            <p>
                                <b>Nội dung:</b>
                                <?php echo $phieuXuatNhap->Content; ?>
                            </p>
                            <p>
                                <b>Loại phiếu:</b>
                                <?php echo $phieuXuatNhap->Type()->Name; ?>
                            </p>
                            <p>
                                <b>Điều kiện nhập kho:</b>
                                <?php echo $phieuXuatNhap->DieuKienNhapKho()->Name; ?>
                            </p>
                            <p>
                                <b>Tình trạng sản phẩm:</b>
                                <?php echo $phieuXuatNhap->TinhTrangSanPham()->Name; ?>
                            </p>
                            <p>
                                <b>Lý Do:</b>
                                <?php echo $phieuXuatNhap->LyDo()->Name; ?>
                            </p>
                            <p>
                                <b>Nhân viên:</b>
                                <?php echo $phieuXuatNhap->UserId()->Name; ?>
                            </p>
                        </div>
                        <div class="col-md-3"></div>
                        <div class="col-md-12">
                            <h3>Danh sách tem sảm phẩm</h3>
                            <table class="table">
                                <tr>
                                    <td>
                                        STT
                                    </td>
                                    <td>
                                        Mã tem
                                    </td>
                                    <td>
                                        Thông tin sản phẩm
                                    </td>
                                </tr>
                                <?php
                                foreach ($DSSanPham as $key => $value) {
                                    $phieuChiTiet = new PhieuXuatNhapChiTiet($value);
                                    ?>
                                    <tr>
                                        <td>
                                            <?php echo $key+1; ?>
                                        </td>
                                        <td>
                                            <?php echo $phieuChiTiet->Code; ?>
                                        </td>
                                        <td>
                                            <?php echo Obj2Html::ThongTinSanPham($phieuChiTiet->SanPhamId); ?>
                                        </td>
                                    </tr>
                                    <?php
                                }
                                ?>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>