<?php
$sanPham = new Module\sanpham\Model\SanPham($sanPham);
$link = "/public/phpqrcode/index.php?data=" . Root_URL . "baohanh/" . $sanPham->Code . "/";
?>
<div class="container" style="margin-top: 15px;" >
    <div class="row "  >
        <section class="col-md-12 pb-10" >
            <div class="row" >
                <form action="" method="POST" enctype="multipart/form-data" >
                    <div class="modal fade" id="MaBaoHanh">
                        <div class="modal-dialog modal-sm">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title">QR code</h4>
                                </div>
                                <div class="modal-body">
                                    <img style="width: 100%" src="<?php echo $link; ?>" class="img img-responsive"  >
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="connectedSortable" >
                        <div class="panel panel-primary">
                            <div class=" panel-heading bg-blue-gradient">
                                <h3 class="panel-title">Chi Tiết Tem Sản Phẩm</h3>
                            </div>
                            <div class="panel-body">
                                <div class="row" >
                                    <div class="col-md-6" >
                                        <fieldset>
                                            <legend>Thông Tin Sản Phẩm</legend>
                                            <?php
                                            \Module\sanpham\Model\TemSanPhamForm::Id($temSanPham->Id)->render();
                                            \Module\sanpham\Model\TemSanPhamForm::Name($temSanPham->Name)->renderHTML();
                                            \Module\sanpham\Model\TemSanPhamForm::MaSanPham($temSanPham->MaSanPham)->renderHTML();
                                            \Module\sanpham\Model\TemSanPhamForm::NgayBatDau($temSanPham->NgayBatDau)->renderHTML();
                                            \Module\sanpham\Model\TemSanPhamForm::NgayKetThuc($temSanPham->NgayKetThuc)->renderHTML();
                                            \Module\sanpham\Model\TemSanPhamForm::KhachHangTieuDung($temSanPham->KhachHangTieuDung, true)->renderHTML();
                                            \Module\sanpham\Model\TemSanPhamForm::Status($temSanPham->Status)->renderHTML();
                                            ?>
                                        </fieldset>
                                    </div>
                                    <div class="col-md-6" >
                                        <fieldset>
                                            <legend>Thông Tin Khách Hàng Tiêu Dùng</legend>
                                            <?php
                                            Module\khachhang\Model\KhachHangTieuDungForm::Id($khachHang->Id)->render();
                                            Module\khachhang\Model\KhachHangTieuDungForm::Name($khachHang->Name)->renderHTML();
                                            Module\khachhang\Model\KhachHangTieuDungForm::CMNN($khachHang->CMNN)->renderHTML();
                                            Module\khachhang\Model\KhachHangTieuDungForm::Phone($khachHang->Phone)->renderHTML();
                                            Module\khachhang\Model\KhachHangTieuDungForm::DiaChi($khachHang->DiaChi)->renderHTML();
                                            Module\khachhang\Model\KhachHangTieuDungForm::GhiChu($khachHang->GhiChu)->renderHTML();
                                            ?>
                                        </fieldset>
                                    </div>
                                </div>
                            </div>
                            <div class="panel-footer" >
                                <a class="btn btn-primary" data-toggle="modal" href='#MaBaoHanh'>Mã QR Code</a>
                                <a class="btn btn-primary" data-toggle="modal" href='#MaBaoHanh'>Yêu Cầu Bảo Hành</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

        </section>
    </div>
</div>
