<style>
    .ResetTable.table tr td {
        padding: 0px 10px;
        vertical-align: middle;
    }

    .form-control {
        border-radius: 0px;
    }

    .ResetFormGroups .form-group {
        margin-bottom: 0px;

    }

    @media screen and (max-width: 600px) {
        .TenCongTy {
            font-size: 16px;
            font-weight: bold;
            margin-top: 16px;
        }

        .title-tembaohanh {
            margin: 0px;
            font-weight: bold;
        }

    }

    legend {
        font-size: 14px;
        display: block;
        width: auto;
        padding-left: 2px;
        padding-right: 2px;
        border: none;
        margin-bottom: 0px;
    }

    fieldset {
        display: block;
        margin-left: 2px;
        margin-right: 2px;
        padding-top: 0.35em;
        padding-bottom: 0.625em;
        padding-left: 0.75em;
        padding-right: 0.75em;
        border: 1px solid;
        margin-bottom: 15px;
    }

    .alert-fixed {
        position: fixed;
        width: 50%;
        top: 20%;
        left: 0px;
        z-index: 99999;
        min-width: 300px;
    }
</style>
<?php
use Model\FormRender;

$temSanPham = new \Module\sanpham\Model\TemSanPham($_Param[0]);

use Model\FormTieuTriDanhGia;
use Model\Notification;
use Module\khachhang\Model\KhachHangTieuDungForm;
use Module\option\Model\Option;
use Module\trungtambaohanh\Model\YeuCauBaoHanhForm;
use PFBC\Element\File;

$idSanPham = $_Param[0];
$_SESSION["KhachHangTieuDung"] = $_SESSION["KhachHangTieuDung"] ?? null;
if ($_SESSION["KhachHangTieuDung"] == null) {
    $khachHang = $temSanPham->KhachHangTieuDung();
} else {
    $khachHang = $_SESSION["KhachHangTieuDung"];
}
$sanPham = new Module\sanpham\Model\SanPham($sanPham);

$link = "/public/phpqrcode/index.php?data=" . Root_URL . "baohanh/" . $idSanPham . "/"


    ?>
<script src="/theme/thanhminhduc/public/baohanhController.js"></script>


<div class="container" style="margin-top: 15px;">
    <div class="row">
        <div class="col-xs-4">
            <a href="/">
                <img src="/public/Logo2.svg" alt="webname" style="height: 80px;" class="img img-responsive">
            </a>
        </div>
        <div class="col-xs-8">
            <h1 class="text-center TenCongTy">CÔNG TY CỔ PHẦN TMDV <br> THÀNH MINH ĐỨC</h1>
            <div class="clearfix"> </div>
        </div>
        <div class="col-md-4 col-xs-12"></div>
        <div class="col-md-8 col-xs-12">
            <p class="text-center" style="margin-top: 10px;"><i class="glyphicon glyphicon-map-marker"></i>
                113 Lâm Thị Hố. Phường Tân Chánh Hiệp, <br> Quận 12, TP. Hồ Chí Minh
            </p>
            <p class="text-center" style="color: red;">
                Hotline, zalo: 0836.206.226 <br>
                Website: https://thanhminhduc.vn
            </p>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-12 pb-10">
            <form action="" method="POST" enctype="multipart/form-data">
                <div class="connectedSortable">
                    <div class="panel-primary">
                        <div class="panel-body">
                            <div class="row">
                                <h4 style="font-weight: bold;" class="text-center title-tembaohanh">Tem Bảo Hành</h4>
                                <div class="col-md-12">
                                    <div class="row">
                                        <fieldset>
                                            <legend>
                                                <b style="font-size: 18px;">
                                                    Thông Tin Sản Phẩm
                                                </b>
                                            </legend>
                                            <table class="table table-bordered">
                                                <tr>
                                                    <td style="width: 100px;">Mã Sản Phẩm:
                                                        <b>
                                                            <?php
                                                            echo $temSanPham->SanPham()->Code;
                                                            ?>
                                                        </b>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td style="width: 200px;">
                                                        Tên Sản Phẩm:
                                                        <b>
                                                            <?php
                                                            echo $temSanPham->SanPham()->Name == "" ? "Chưa xác định" : $temSanPham->SanPham()->Name;
                                                            ?>
                                                        </b>
                                                    </td>
                                                </tr>
                                            </table>
                                        </fieldset>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="row">
                                        <?php
                                        if ($temSanPham->Status != Module\sanpham\Model\TemSanPham::Active) {
                                            ?>

                                            <fieldset>
                                                <legend>
                                                    <label style="font-weight: normal;cursor: pointer">
                                                        <b style="font-size: 18px;"> Yêu cầu kích hoạt</b>
                                                    </label>
                                                </legend>

                                                <div class="">
                                                    <?php
                                                    if ($temSanPham->SanPham()->Name) {
                                                        ?>
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <?php
                                                                YeuCauBaoHanhForm::HoTen($khachHang->Name)->renderHTML();
                                                                ?>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <?php
                                                                YeuCauBaoHanhForm::SDT($khachHang->Phone)->renderHTML();
                                                                ?>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <?php
                                                                YeuCauBaoHanhForm::TinhThanh($khachHang->TinhThanh, "TinhThanhId", "#QuanHuyenId")->renderHTML();
                                                                ?>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <?php
                                                                YeuCauBaoHanhForm::QuanHuyen($khachHang->QuanHuyen, $khachHang->TinhThanh, "QuanHuyenId")->renderHTML();
                                                                ?>
                                                            </div>
                                                            <div class="col-md-12">
                                                                <?php
                                                                YeuCauBaoHanhForm::DiaChi($khachHang->DiaChi)->renderHTML();
                                                                YeuCauBaoHanhForm::MaTem($temSanPham->Code, null, true)->render();
                                                                ?>
                                                            </div>
                                                        </div>
                                                        <div class="text-right">
                                                            <input type="hidden" name="BtnYeuCauKichHoat" value="1">
                                                            <button id="YeuCauKichHoat" type="submit"
                                                                class="btn btn-submit btn-primary">Yêu cầu kích hoạt</button>
                                                        </div>
                                                        <?php
                                                    } else {
                                                        ?>
                                                        <p style="color:red">Tem bảo hanh chưa có thông tin sản phẩm
                                                            <b>
                                                                Liên hệ SĐT <a href="tel:0329.687.989">0329.687.989</a>
                                                            </b> Để được hỗ trợ
                                                        </p>
                                                        <?php
                                                    }
                                                    ?>

                                                </div>

                                            </fieldset>
                                            <?php
                                        } else {
                                            ?>
                                            <fieldset>
                                                <legend>
                                                    <label style="font-weight: normal;cursor: pointer">
                                                        <b style="font-size: 18px;"> Thông Tin khách hàng</b>
                                                    </label>
                                                </legend>
                                                <table class="table table-bordered">
                                                    <tr>
                                                        <td>Họ & Tên:
                                                            <b>
                                                                <?php echo $khachHang->Name ?>
                                                            </b>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>SĐT: <b>
                                                                <?php echo $khachHang->Phone ?>
                                                            </b>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>Địa Chỉ: <b>
                                                                <?php echo $khachHang->DiaChi() ?>
                                                            </b>
                                                        </td>
                                                    </tr>
                                                </table>
                                                <div class="text-right">
                                                    <a class="btn btn-primary" target="_self" data-toggle="modal"
                                                        href='#SuaThongTin'>Sửa thông tin</a>
                                                </div>
                                            </fieldset>
                                            <?php
                                        }
                                        ?>

                                        <fieldset>
                                            <legend>
                                                <b style="font-size: 18px;">
                                                    Thông Tin Bảo Hành
                                                </b>
                                            </legend>
                                            <table class="table table-bordered">
                                                <tr>
                                                    <td colspan="2">
                                                        Ngày Bắt Đầu Bảo Hành:
                                                        <b>
                                                            <?php
                                                            echo $temSanPham->NgayBatDau();
                                                            ?>
                                                        </b>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td colspan="2">
                                                        Thời Gian Bảo Hành:
                                                        <b>
                                                            <?php
                                                            echo $temSanPham->ThangKetThuc();
                                                            ?>
                                                        </b>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td colspan="2">
                                                        Ngày Kết Thúc:
                                                        <b>
                                                            <?php
                                                            echo $temSanPham->NgayKetThuc();
                                                            ?>
                                                        </b>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td colspan="2">
                                                        Tình Trạng:
                                                        <b>
                                                            <?php
                                                            echo $temSanPham->Status()->Name;
                                                            ?>
                                                        </b>
                                                    </td>
                                                </tr>
                                            </table>
                                        </fieldset>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="">
                            <a href="/index/scan/" class="btn btn-primary">
                                Quét mã
                                <i class="fa fa-camera"></i>
                            </a>
                            <a class="btn btn-primary" data-toggle="modal" href='#MaBaoHanh'>Mã QR Code</a>
                            <a class="btn btn-primary" target="_self" data-toggle="modal" href='#DanhGiaHoTro'>Đánh giá
                                hỗ trợ</a>
                            <?php
                            if ($temSanPham->Status == Module\sanpham\Model\TemSanPham::Active) {
                                ?>
                                <a class="btn btn-primary" target="_self" data-toggle="modal" href='#YeuCauBaoHanh'>Yêu cầu
                                    bảo hành</a>
                                <?php
                            }
                            ?>


                        </div>
                    </div>
                </div>
                <?php
                if ($temSanPham->Status != Module\sanpham\Model\TemSanPham::Active) {
                    ?>
                    <div class="text-center">
                        <img src="/public/baohanh/ChuaKhachHang.jpg?php echo time(); ?>" class="img img-responsive"
                            alt="hướng dẫn bảo hành">
                    </div>
                    <?php
                }
                ?>
                <?php
                if ($temSanPham->Status == Module\sanpham\Model\TemSanPham::Active) {
                    ?>
                    <div class="text-center">
                        <img src="/public/baohanh/CoKhachHang.jpg?v=<?php echo time(); ?>" class="img img-responsive"
                            alt="hướng dẫn bảo hành">
                    </div>
                    <?php
                }
                ?>

            </form>
        </div>
    </div>
</div>


<div class="modal fade" id="YeuCauBaoHanh">
    <form action="" enctype="multipart/form-data" method="POST">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Yêu Cầu Bảo Hành</h4>
                </div>
                <div class="modal-body">
                    <?php
                    \Module\trungtambaohanh\Model\YeuCauBaoHanhForm::NoiDung()->renderHTML();
                    ?>
                    <div class="row">
                        <div class="col-md-6">
                            <?php
                            \Module\trungtambaohanh\Model\YeuCauBaoHanhForm::TinhThanh($khachHang->TinhThanh)->renderHTML();
                            ?>
                        </div>
                        <div class="col-md-6">
                            <?php
                            \Module\trungtambaohanh\Model\YeuCauBaoHanhForm::QuanHuyen($khachHang->QuanHuyen, $khachHang->TinhThanh)->renderHTML();
                            ?>
                        </div>
                        <div class="col-md-12">
                            <?php
                            \Module\trungtambaohanh\Model\YeuCauBaoHanhForm::DiaChi($khachHang->DiaChi)->renderHTML();
                            ?>
                        </div>
                        <div class="col-md-6">
                            <?php
                            \Module\trungtambaohanh\Model\YeuCauBaoHanhForm::SDT($khachHang->Phone)->renderHTML();
                            ?>
                        </div>
                        <div class="col-md-6">
                            <?php
                            \Module\trungtambaohanh\Model\YeuCauBaoHanhForm::NgayBaoHanh(null, null, $temSanPham->NgayKetThuc)->renderHTML();
                            ?>
                        </div>
                    </div>
                    <?php
                    \Module\trungtambaohanh\Model\YeuCauBaoHanhForm::MaTem($temSanPham->Code, null, true)->render();
                    \Module\trungtambaohanh\Model\YeuCauBaoHanhForm::KhachHangTieuDung(
                        $temSanPham->KhachHangTieuDung,
                        null,
                        true
                    )->render();

                    $fForm = new FormRender(new File("", "HinhLoi", [
                        "accept" => "image/*",
                        "class" =>"hidden"
                    ]));
                    ?>
                    <label style="border: dashed 2px green;width: 100%;text-align: center;" >
                        <?php
                        $fForm->renderHTML();
                        ?>
                        <img style="height: 40px;" src="/public/Camera.png" />
                        <p style="margin: 0px;" >
                            Hình sản phẩm
                        </p>
                    </label>
                </div>
                <div class="modal-footer">
                    <input type="hidden" name="BtnYeuCauBaoHanh" value="1">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Thoát</button>
                    <button type="submit" class="btn btn-primary">Gửi yêu cầu</button>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="modal fade" id="MaBaoHanh">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">QR code</h4>
            </div>
            <div class="modal-body">
                <img style="width: 100%" src="<?php echo $link; ?>" class="img img-responsive">
                <span>
                    <?php echo $idSanPham ?>
                </span>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="DanhGiaHoTro">
    <form action="" enctype="multipart/form-data" onsubmit="return(SubmitFormDanhGiaHoTro())" id="FormDanhGiaHoTro"
        enctype="multipart/form-data" method="POST">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Đánh Giá Hỗ Trợ</h4>
                </div>
                <div class="modal-body">
                    <table class="table table-bordered ResetTable">
                        <?php
                        try {
                            $option = new Option();
                            $options = $option->GetAll2OptionsByGroups(Option::TieuChiDanhGia);
                            foreach ($options as $key => $value) {
                                ?>
                                <tr>
                                    <td>
                                        <?php echo $value; ?>
                                    </td>
                                    <td class="ResetFormGroups">
                                        <?php FormTieuTriDanhGia::TieuTri(null, $key, "")->renderHtml(); ?>
                                    </td>
                                </tr>
                                <?php
                            }
                        } catch (Exception $th) {
                            echo $th;
                        }
                        ?>
                    </table>
                    <div>
                        <?php
                        FormTieuTriDanhGia::MaTem($_Param[0])->render();
                        FormTieuTriDanhGia::Comment("")->renderHtml();

                        ?>
                        <div>
                            <label style="cursor: pointer;text-align: center;border: 2px dashed green;width: 100%;">
                                Chọn file
                                <?php
                                FormTieuTriDanhGia::File("", "FileChonFile")->render();
                                ?>
                                <div style="height: 70px;">
                                    <img src="" id="previewImg" style="height: 70px;">
                                </div>
                            </label>
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Thoát</button>
                    <button type="submit" class="btn btn-primary">Gửi đánh giá</button>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="modal fade" id="SuaThongTin">
    <form action="" enctype="multipart/form-data" enctype="multipart/form-data" method="POST">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Thông tin khách hàng</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <?php
                            KhachHangTieuDungForm::MaTem($temSanPham->Code)->render();
                            KhachHangTieuDungForm::Name($khachHang->Name)->renderHTML();
                            ?>
                        </div>
                        <div class="col-md-6">
                            <?php
                            KhachHangTieuDungForm::Phone($khachHang->Phone)->renderHTML();
                            ?>
                        </div>
                        <div class="col-md-4 hidden">
                            <?php
                            KhachHangTieuDungForm::KhuVuc($khachHang->KhuVuc)->renderHTML();
                            ?>
                        </div>
                        <div class="col-md-6">
                            <?php
                            KhachHangTieuDungForm::TinhThanh($khachHang->TinhThanh, "#KhachHangTieuDungQuan_Box")->renderHTML();
                            ?>
                        </div>
                        <div class="col-md-6">
                            <?php
                            KhachHangTieuDungForm::QuanHuyen($khachHang->QuanHuyen, $khachHang->TinhThanh, "KhachHangTieuDungQuan_Box")->renderHTML();
                            ?>
                        </div>
                    </div>
                    <?php
                    KhachHangTieuDungForm::DiaChi($khachHang->DiaChi)->renderHTML();
                    KhachHangTieuDungForm::GhiChu($khachHang->GhiChu)->renderHTML();
                    ?>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-submit btn-primary"> Lưu </button>
                </div>
            </div>
        </div>
    </form>

</div>

<script>
    $(".alert").hide(5000);
    function SubmitFormDanhGiaHoTro() {
        if (confirm(`Nhấn “Ok” để gửi đánh giá dịch vụ. `) == false) {
            return false;
        }
    }

    function onSubmit() {
        if (confirm(`Nhấn "Đồng ý" để gửi yêu cầu kích hoạt Yêu cầu sẽ được thực hiện trong vòng 24h. Cảm ơn Quý khách!`) == false) {
            return;
        }
        var dataFormArray = $("form#yeucaukichhoat").serializeArray();

        if (dataFormArray[1]["value"] == "") {

        }
        var dataFormString = $("form#yeucaukichhoat").serialize();
        $.ajax({
            url: '/index/yeucaukichhoat/',
            type: 'POST',
            data: dataFormString,
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            success: function (response) {
                alert(`Cảm ơn Quý khách đã gửi yêu cầu kích hoạt sản phẩm`);
                window.location.reload();
            },
            error: function () {
                alert("error");
            }
        });
        return false;
    };
    $(function () {
        $("#FileChonFile").change(function () {
            var file = $(this).get(0).files[0];
            if (file) {
                var reader = new FileReader();
                reader.onload = function () {
                    $("#previewImg").attr("src", reader.result);
                }

                reader.readAsDataURL(file);
            }
        });
        $("form").submit(function () {
            $(".btn-submit").attr("disabled", true);
            $(".btn-submit").text("Đang gửi ...");
        })
        $("select.AjaxHTML").each(function () {
            try {
                var dataHTML = $(this).data();
                var self = $(this);
                var object = dataHTML.object;
                self.change(function () {
                    if (dataHTML.values == true) {
                        var url = dataHTML.url;
                        url = url + self.val();
                        // alert(url);
                        $.ajax({
                            url: url
                        }).done(function (res) {
                            // alert(res);
                            $(object).html(res);

                        });
                    }
                });
            } catch (error) {
                // alert(error)
                console.log(error);
            }

        });
    })
</script>

<?php
$alert = (new Notification())->GetContent();
new Notification(null);
if ($alert->type != null) {
    ?>
    <div class="modal fade modal-<?php echo $alert->type ?>" id="ThongBao">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <p class="text-center">
                        <?php echo $alert->content; ?>
                    </p>
                </div>
                <div class="text-right" style="padding: 10px;">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $("#ThongBao").modal('show');
        });
    </script>
    <?php
}
?>