<style>
    @media screen and (max-width: 600px){
        .TenCongTy{
            font-size: 16px;
            font-weight: bold;
            margin-top: 16px;
        }
        .title-tembaohanh{
            margin: 0px;
            font-weight: bold;
        }
    }
</style>
<?php
//$temSanPham = new \Module\sanpham\Model\TemSanPham();

$sanPham = new Module\sanpham\Model\SanPham($sanPham);
$link = "/public/phpqrcode/index.php?data=" . Root_URL . "baohanh/" . $sanPham->Code . "/";
?>
<div class="container" style="margin-top: 15px;" >

    <div class="row" >
        <div class="col-xs-4" >
            <a href="/">
                <img src="/public/Logo2.svg" alt="webname" style="height: 80px;" class="img img-responsive">
            </a>
        </div>
        <div class="col-xs-8" >
            <h1 class="text-center TenCongTy" >CÔNG TY CỔ PHẦN TMDV <br> THÀNH MINH ĐỨC</h1>
        </div>
        <div class="col-md-12" >
            <div class="clearfix" >  </div>
            <p class="text-center" style="margin-top: 10px;" ><i class="glyphicon glyphicon-map-marker" ></i>113/49/21 Đường TCH05, Khu phố 10, Phường Tân Chánh Hiệp, Quận 12, Thành phố Hồ Chí Minh, Việt Nam</p>
            <p class="text-center" style="color: red;text-transform: capitalize" >hotline: 08 3620 6226 | Email: smartkitchenware.tmd@gmail.com | Zalo: 08 3620 6226</p>
        </div>
        <section class="col-md-12 pb-10" >
            <form action="" method="POST" enctype="multipart/form-data" >

                <div class="connectedSortable" >
                    <div class="panel-primary">
                        <div class=" ">
                        </div>
                        <div class="panel-body">
                            <div class="row" >
                                <h3 class="text-center title-tembaohanh" >Tem Bảo Hành</h3>
                                <div class="col-md-6" >
                                    <fieldset>
                                        <legend>Thông Tin Bảo Hành</legend>
                                        <table class="table table-bordered" >
                                            <tr>
                                                <th style="width: 200px;" >Tên Sản Phẩm</th>
                                                <td>
                                                    <?php
                                                    echo $temSanPham->SanPham()->Name;
                                                    ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <th style="width: 100px;" >Mã Sản Phẩm</th>
                                                <td>
                                                    <?php
                                                    echo $temSanPham->SanPham()->Name;
                                                    ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <th colspan="2" >
                                                    <label>Ngày Bắt Đầu Bảo Hành:</label>
                                                    <?php
                                                    echo $temSanPham->NgayBatDau();
                                                    ?>
                                                </th>
                                            </tr>
                                            <tr>
                                                <th colspan="2" >
                                                    <label>Thời Gian Bảo Hành:</label>
                                                    <?php
                                                    echo $temSanPham->ThangKetThuc();
                                                    ?>
                                                </th>
                                            </tr>
                                            <tr>
                                                <th colspan="2" >
                                                    <label>Ngày Kết Thúc:</label>
                                                    <?php
                                                    echo $temSanPham->NgayKetThuc();
                                                    ?>
                                                </th>
                                            </tr>
                                            <tr>
                                                <th colspan="2" >
                                                    <label>Tình Trạng:</label>
                                                    <?php
                                                    echo $temSanPham->Status()->Name;
                                                    ?>
                                                </th>
                                            </tr>
                                        </table>

                                    </fieldset>
                                </div>
                                <div class="col-md-6" >
                                    <fieldset>
                                        <legend>Thông Tin Khách</legend>
                                        <table class="table table-bordered" >
                                            <tr>
                                                <th style="width: 100px;" >Họ & Tên</th>
                                                <td>
                                                    <?php
                                                    echo $khachHang->Name;
                                                    ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <th>SĐT</th>
                                                <td>
                                                    <?php
                                                    echo $khachHang->Phone;
                                                    ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td colspan="2" >
                                                    <label>Địa Chỉ</label>
                                                    <?php
                                                    echo $khachHang->DiaChi;
                                                    ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td colspan="2" >
                                                    <label>Ghi Chú: </label>
                                                    <?php
                                                    echo $khachHang->GhiChu;
                                                    ?>
                                                </td>
                                            </tr>
                                        </table>

                                    </fieldset>
                                </div>
                            </div>
                        </div>
                        <div class="" >
                            <a class="btn btn-primary" data-toggle="modal" href='#MaBaoHanh'>Mã QR Code</a>
                            <?php
                            if ($temSanPham->Status == Module\sanpham\Model\TemSanPham::Active) {
                                ?>
                                <a class="btn btn-primary" data-toggle="modal" href='#yeuCauBaoHanh'>Yêu Cầu Bảo Hành</a>
                                <?php
                            }
                            ?>
                            <a href="/sanpham/temsanpham/detailbysanpham/<?php echo $temSanPham->Code; ?>/" class="btn btn-primary" >Cập Nhập Tem Bảo Hành</a>
                        </div>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>
<div class="modal fade" id="MaBaoHanh">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">QR code</h4>
            </div>
            <div class="modal-body">
                <img style="width: 100%" src="<?php echo $link; ?>" class="img img-responsive"  >
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="yeuCauBaoHanh"  >
    <form action="" enctype="multipart/form-data" method="POST" >
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Yêu Cầu Bảo Hành</h4>
                </div>
                <div class="modal-body">
                    <?php
                    \Module\trungtambaohanh\Model\YeuCauBaoHanhForm::NoiDung()->renderHTML();
                    \Module\trungtambaohanh\Model\YeuCauBaoHanhForm::DiaChi($khachHang->DiaChi)->renderHTML();
                    ?>
                    <div class="row">
                        <div class="col-md-6" >
                            <?php
                            \Module\trungtambaohanh\Model\YeuCauBaoHanhForm::SDT($khachHang->Phone)->renderHTML();
                            ?>
                        </div>
                        <div class="col-md-6" >
                            <?php
                            \Module\trungtambaohanh\Model\YeuCauBaoHanhForm::NgayBaoHanh()->renderHTML();
                            ?>
                        </div>
                    </div>
                    <?php
                    \Module\trungtambaohanh\Model\YeuCauBaoHanhForm::MaTem($temSanPham->Code, null, true)->render();
                    \Module\trungtambaohanh\Model\YeuCauBaoHanhForm::KhachHangTieuDung($temSanPham->KhachHangTieuDung, null, true)->render();
                    ?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Thoát</button>
                    <button type="submit" class="btn btn-primary">Gửi yêu cầu</button>
                </div>
            </div>
        </div>
    </form>
</div>