<section class="mainslide">
    <div id="carouselExampleIndicators1" class="carousel slide" data-ride="carousel"  >
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active" style="background-image: url('/public/theme/TMD/images/banner.jpg')"  > </div>
            <div class="carousel-item" style="background-image: url('/public/theme/TMD/images/banner.jpg')"> </div>
            <div class="carousel-item" style="background-image: url('/public/theme/TMD/images/banner.jpg')"> </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators1" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a> <a class="carousel-control-next" href="#carouselExampleIndicators1" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a> </div>
    <div class="danhSachDoiTac bg-dark60 p-2 " >
        <div class="container " >
            <div class="owl-custom DanhSachDoiTac owl-carousel owl-theme" data-responsive='{"380":{"items":2},"600":{"items":4},"1000":{"items":8}}'  data-dots-each="true" data-dots="false" data-loop="true" data-nav="true" data-margin="10" >
                <div class="item "> <a href="#"> <img class="" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
                <div class="item "> <a href="#"> <img class="" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
                <div class="item "> <a href="#"> <img class="" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
                <div class="item "> <a href="#"> <img class="" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
                <div class="item "> <a href="#"> <img class="" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
            </div>
        </div>
    </div>
</section>
<section class="Content mt-4">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-justify">
            </div>
        </div>
    </div>
</section>
<section class="">
    <div class=" ">
        <div class=" ">
            <div>
                <div class="bg-theme taisaochonchungtoi p-3">
                    <div class="container">
                        <div class="row p-4">
                            <div class="col-md-8  ">
                                <h2 class="text-center">Gọi Cho Chúng Tôi Để Được Tư Vấn</h2>
                            </div>
                            <div class="col-md-4 ">
                                <h2 class="">
                                    <i class="fa fa-phone " ></i> __HotLine__
                                </h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="BaiVietNoiBat bg-gray p-3 pt-4" >
    <div class="container">
        <div class="row ">
            <div class="col-md-12">
                <h2 class="text-center fw-bold fs-3 p-3" >Dịch Vụ</h2>
            </div>
            <div class="col-md-6">
                <div class="card border-radius-0 BaiVietNoiBat-Main "> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <hr style="border-bottom: 1px solid #fff;"  >
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content. </p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12 mb-4">
                        <div class="card border-radius-0 BaiVietNoiBat2"> <img  class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap">
                            <div class="">
                                <h5 class="card-title">Card title</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="card border-radius-0 BaiVietNoiBat3"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap">
                            <div class="">
                                <h5 class="card-title">Card title</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="card border-radius-0 BaiVietNoiBat3"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap">
                            <div class="">
                                <h5 class="card-title">Card title</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="card border-radius-0 BaiVietNoiBat3"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap">
                            <div class=" ">
                                <h5 class="card-title">Card title</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="card border-radius-0 BaiVietNoiBat3"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap">
                            <div class=" ">
                                <h5 class="card-title">Card title</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="" >
    <div class=" ">
        <div class=" ">
            <div>
                <div class="bg-theme taisaochonchungtoi p-3">
                    <h2 class="title taisaochonchungtoi-title text-center">Tại sao chọn chúng tôi?</h2>
                    <hr>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-4 item">
                                        <h2 class="mb-0 text-center" >Chuyên Nghiệp</h2>
                                        <p class="text-center" >Chuyên nghiệp trong tư vấn, làm hồ sơ </p>
                                    </div>
                                    <div class="col-md-4 item">
                                        <h2 class="mb-0 text-center" >Chính Xác</h2>
                                        <p class="text-center" >Chúng tôi cam kết làm việc chính xác đến từng chi tiết </p>
                                    </div>
                                    <div class="col-md-4 item">
                                        <h2 class="mb-0 text-center" >Hiệu Quả</h2>
                                        <p class="text-center" >Làm việc hiệu quả cho từng chi phí của khách hàng </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="ChungToiLaAi bg-gray p-3 pt-4" >
    <div class="container">
        <div class="row ">
            <div class="col-md-12">
                <h2 class="text-center fw-bold fs-3 p-3" >Chúng Tôi Là Ai?</h2>
            </div>
            <div class="col-md-4">
                <div class="card border-radius-0   ">
                    <h2 class="card-title text-center fs-4 pt-5">Card title</h2>
                    <div class="card-body text-justify">
                        <hr style="border-bottom: 1px solid #fff;"  >
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content. </p>
                    </div>
                    <a href="#" class="btn bnt-primary">Xem Thêm <i class="fa fa-angle-double-right"  ></i></a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card border-radius-0   ">
                    <h2 class="card-title text-center fs-4 pt-5">Card title</h2>
                    <div class="card-body text-justify">
                        <hr style="border-bottom: 1px solid #fff;"  >
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content. </p>
                    </div>
                    <a href="#" class="btn bnt-primary">Xem Thêm <i class="fa fa-angle-double-right"  ></i></a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card border-radius-0   ">
                    <h2 class="card-title text-center fs-4 pt-5">Card title</h2>
                    <div class="card-body text-justify">
                        <hr style="border-bottom: 1px solid #fff;"  >
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content. </p>
                    </div>
                    <a href="#" class="btn bnt-primary">Xem Thêm <i class="fa fa-angle-double-right"  ></i></a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="bg-dark" >
    <div class="container">
        <h2 class="p-3 fs-3 text-center color-while" >Khách Hàng Nói Về Chúng Tôi</h2>
        <div id="carouselExampleIndicators2" class="NhanXetCuaKhacHang carousel slide" data-ride="carousel"  >
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <div class="carousel-caption">
                        <h5> Third slide Heading</h5>
                        <p>
                        <blockquote>Third slide Caption</blockquote>
                        </p>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="carousel-caption">
                        <h5> Third slide Heading</h5>
                        <p>
                        <blockquote>Third slide Caption</blockquote>
                        </p>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="carousel-caption">
                        <h5> Third slide Heading</h5>
                        <p>
                        <blockquote>Third slide Caption</blockquote>
                        </p>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators2" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a> <a class="carousel-control-next" href="#carouselExampleIndicators2" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a> </div>
    </div>
</section>
<section>
    <div class="container p-4" >
        <div class="owl-custom DanhSachDoiTac owl-carousel owl-theme" data-responsive='{"380":{"items":2},"600":{"items":4},"1000":{"items":6}}'  data-dots-each="true" data-dots="false" data-loop="true" data-nav="true" data-margin="10" >
            <div class="card item "> <a href="#"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
            <div class="card item "> <a href="#"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
            <div class="card item "> <a href="#"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
            <div class="card item "> <a href="#"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
            <div class="card item "> <a href="#"> <img class="card-img-top" src="/public/theme/TMD/images/card-img.png" alt="Card image cap"> </a> </div>
        </div>
    </div>
</section>