<ol class="breadcrumb">
     <li>Quét Mã</li>
</ol>
<script src="/Module/dashboard/public/html5-qrcode.min.js" type="text/javascript"></script>
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div id="qr-reader" style="width:100%;height: auto;margin: auto;"></div>
            <div class="thongbao bg-green" id="alertCode"></div>
            <div id="error"></div>
            <div id="countResults"></div>
            <label>Nội Dung</label>
            <textarea style="display: none;width: 100%;height: 50px;" id="qr-reader-results"></textarea>
        </div>
    </div>
</div>
<script>
    class NhapMa {
        content;
        idElement;
        code;
        constructor(content) {
            this.content = content
        }
        GetCodeByQrcode() {

            var res = this.content.split("/");
            // alert(this.content);
            // alert(res[3]);
            return res[3];
        }
        async SaveCode() {
            this.code = this.GetCodeByQrcode();
            var CodeTem = this.code;
            var link = `\\baohanh\\${CodeTem}`; 
            window.location.href=link;
        }

    }

    function docReady(fn) {
        // see if DOM is already available
        if (document.readyState === "complete"
            || document.readyState === "interactive") {
            // call on next available tick
            setTimeout(fn, 100);
        } else {
            document.addEventListener("DOMContentLoaded", fn);
        }
    }
    docReady(function () {
        try {
            var resultContainer = document.getElementById('qr-reader-results');
            var lastResult, countResults = 0;
            function onScanSuccess(decodedText, decodedResult) {
                if (decodedText !== lastResult) {
                    ++countResults;
                    lastResult = decodedText;
                    // Handle on success condition with the decoded message.
                    resultContainer.innerHTML = `${decodedText}`;
                    var nhapMa = new NhapMa(decodedText);
                    nhapMa.SaveCode();

                    // countResultsHtml = document.getElementById("countResults");
                    // countResultsHtml.innerHTML = "Số Lần Quét: " + countResults;
                }
            }
            var html5QrcodeScanner = new Html5QrcodeScanner(
                "qr-reader", { fps: 10, qrbox: 250 });
            html5QrcodeScanner.render(onScanSuccess);
        } catch (error) {
            var errorHtml = document.getElementById("error");
            errorHtml.innerHTML += error;
        }
    });
</script>