<?php
$form = new \Model\Form();
?>
<div class="am-pagetitle">
    <div class="btn-group" >
        <a href="/user/index" class="btn btn-primary" >Nội Dung Mail</a>
    </div>
</div>
<div class="container" >
    <div class="am-pagebody" >
        <div class="centercontent">
            <div class="card pd-20 mg-t-5">
                <h6 class="card-body-title">Thêm Nội Dung Mail</h6>
                <form action="" method="POST" enctype="multipart/form-data" >
                    <div >
                        <div class="row" >
                            <?php
                            $Alert = new Application\Model\Alert();
                            $cAlert = $Alert->getAlert();
                            if ($cAlert) {
                                ?>
                                <div class="col-md-12 alert-<?php echo $cAlert["Type"] ?> alert" >
                                    <?php echo $cAlert["Content"] ?>
                                </div>
                                <?php
                            }
                            ?>
                            <div class="col-md-12" >
                                <div class="form-group">
                                    <label for="">Mã</label>
                                    <?php
                                    Module\mail\Model\MailContentForm::Code(["required" => "", "name" => "Mail[Code]", "class" => "form-control"])->render();
                                    ?>
                                </div>
                                <div class="form-group">
                                    <label for="">Tên Mail</label>
                                    <?php
                                    Module\mail\Model\MailContentForm::Name(["required" => "", "name" => "Mail[Name]", "class" => "form-control"])->render();
                                    ?>
                                </div>
                                <div class="form-group">
                                    <label for="">Nội Dung</label>
                                    <?php
                                    Module\mail\Model\MailContentForm::Content(["required" => "", "name" => "Mail[Content]", "class" => "ckeditor"])->render();
                                    ?>
                                </div>
                                <div class="form-group">
                                    <label for=""></label>
                                    <?php
                                    $form->btnSave()->render();
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
