<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Log in</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.5 -->
        <link rel="stylesheet" href="/public/admin/bootstrap/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="/public/admin/dist/css/AdminLTE.min.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="/public/admin/plugins/iCheck/square/blue.css">
    </head>
    <body class="hold-transition login-page">

        <?php
        $alert = \Common\Alert::getAlert();
        if ($alert) {
            ?>
            <div class="alert alert-<?php echo $alert["Type"]; ?>" >
                <?php echo $alert["Content"]; ?>
            </div>
            <?php
        }
        include $_Content;
        ?>
        <!-- jQuery 2.1.4 -->
        <script src="/public/admin/plugins/jQuery/jQuery-2.1.4.min.js"></script>
        <!-- Bootstrap 3.3.5 -->
        <script src="/public/admin/bootstrap/js/bootstrap.min.js"></script>
        <!-- iCheck -->
        <script src="/public/admin/plugins/iCheck/icheck.min.js"></script>
        <script>
            $(function() {
                setTimeout(function() {
                    $(".alert").hide();
                    console.log("asda");
                }, 3000);
                $('input').iCheck({
                    checkboxClass: 'icheckbox_square-blue',
                    radioClass: 'iradio_square-blue',
                    increaseArea: '20%'
                });
            });
        </script>
    </body>
</html>
