<?php
$bk = new theme\backend\backend();
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Trang Quản Trị</title>
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <?php
        $bk->head();
        ?>
        <script src="/public/admin/plugins/jQuery/jquery-3.5.1.js" type="text/javascript" ></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="/public/partials/loaderpartials/backend/backendconfig.js?v=<?php echo filemtime("public/partials/loaderpartials/backend/backendconfig.js") ?>" type="text/javascript" ></script>

    </head>
    <body class="hold-transition skin-blue layout-top-nav" ng-cloak="TRUE" ng-app="rootApp"  >
        <div class="wrapper">
            <?php
            $bk->MenuNVKT();
            ?>
            <div class="content-wrapper">
                <section class="">
                    <?php
                    Common\Alert::showAlert();
                    include $_Content;
                    ?>
                </section>
            </div>
            <?php
            $bk->footer();
            ?>
        </div>
        <?php
        $bk->js();
        echo Application\Html\Js::GetJS();
        ?>
    </body>
</html>
