<?php

use Common\Common;
use Model\FormTieuTriDanhGia;
use Model\PhanAnh\PhanAnh;
use Model\PhanAnh\PhanAnhLog;
use Model\PhanAnh\XuLyPhanAnh;
use Module\option\Model\Option;

$item = new PhanAnh($data["item"]);

$options = Option::GetAll2OptionsByGroupsID(Option::TieuChiDanhGia);
$ketQuaDanhGia = $item->PhanAnhChiTiet();
// var_dump($ketQuaDanhGia);
$itemsTieuTri = [];
foreach ($ketQuaDanhGia as $v) {
    $itemsTieuTri[$v["TieuTri"]] = $v["KetQua"];
}
// var_dump($itemsTieuTri);

?>
<ol class="breadcrumb">
    <li>
        <a href="/dashboard/">Dashboard</a>
    </li>
    <li>
        <a href="/dashboard/phananh/">Danh sách đánh giá</a>
    </li>
    <li>
        Xem
    </li>
</ol>
<div class="container-fluid ">
    <section class="col-md-12 pb-10 mt-20">
        <div class="connectedSortable">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Nội dung đánh giá</h3>
                    <div class="pull-right">
                        <a href="/dashboard/phananh/" class="btn btn-primary"> Quay lại</a>
                    </div>

                </div>
                <div class="box-body  ">
                    <div class="col-md-3">
                        <form action="/dashboard/phananh/post/" method="POST">
                            <fieldset>
                                <legend>Xử lý đánh giá</legend>
                                <?php
                                $formPhanAnh = new XuLyPhanAnh();
                                $formPhanAnh->Id($item->Id)->render();
                                $formPhanAnh->TinhTrang($item->TinhTrang)->renderHTML();
                                $formPhanAnh->Comment()->renderHTML();
                                ?>
                                <button class="btn btn-success">Lưu</button>
                            </fieldset>
                        </form>

                    </div>
                    <div class="col-md-9">

                        <div role="tabpanel">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#ThongTinPhanAnh" aria-controls="ThongTinPhanAnh" role="tab" data-toggle="tab">
                                        Thông tin đánh giá
                                    </a>
                                </li>
                                <li role="presentation">
                                    <a href="#ThongTinPhanAnhLog" aria-controls="ThongTinPhanAnhLog" role="tab" data-toggle="tab">
                                        Lịch sử xử lý
                                    </a>
                                </li>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="ThongTinPhanAnh">
                                    <table class="table table-border">
                                        <tr>
                                            <td colspan="2">
                                                <h4><b>Thông tin đánh giá</b></h4>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Mã</td>
                                            <td><?php echo $item->Code; ?></td>
                                        </tr>
                                        <tr>
                                            <td>Tình trạng</td>
                                            <td><?php echo $item->TinhTrang()->Name; ?></td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <h4><b>Thông tin sản phẩm</b></h4>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Sản Phẩm</td>
                                            <td><?php echo $item->TemSanPham()->SanPham()->Name; ?></td>
                                        </tr>
                                        <tr>
                                            <td>Đại Lý</td>
                                            <td><?php echo $item->TemSanPham()->SanPham()->DaiLy()->Name; ?></td>
                                        </tr>

                                        <tr>
                                            <td colspan="2">
                                                <h4><b>Khách hàng tiêu dùng</b></h4>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Họ Tên</td>
                                            <td><?php echo $item->TemSanPham()->KhachHangTieuDung()->Name; ?></td>
                                        </tr>
                                        <tr>
                                            <td>SĐT</td>
                                            <td><?php echo $item->TemSanPham()->KhachHangTieuDung()->Phone; ?></td>
                                        </tr>
                                        <tr>
                                            <td>Địa chỉ</td>
                                            <td><?php echo $item->TemSanPham()->KhachHangTieuDung()->DiaChi(); ?></td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <h4><b>Kết quả đánh giá</b></h4>
                                            </td>
                                        </tr>

                                        <?php
                                        FormTieuTriDanhGia::SetValueTieuTri($itemsTieuTri);
                                        $form = new FormTieuTriDanhGia();

                                        foreach ($options as $code => $title) {
                                            $op = new Option($code);
                                        ?>
                                            <tr>
                                                <td><?php echo $form->TieuTri(null, $op->Code, $title)->render(); ?></td>
                                                <td><?php echo $title; ?></td>
                                            </tr>
                                        <?php
                                        }
                                        ?>
                                    </table>
                                    <table class="table table-border">
                                        <tr>
                                            <td>
                                                <h4><b>Nội dung</b></h4>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><?php echo strip_tags($item->Content); ?></td>
                                        </tr>
                                    </table>
                                    <fieldset>
                                        <legend>Hình ảnh</legend>
                                        <img style="height: 200px;" class="img img-responsive" src="<?php echo $item->HinhAnh; ?>">
                                    </fieldset>

                                </div>
                                <div role="tabpanel" class="tab-pane" id="ThongTinPhanAnhLog">
                                    <?php
                                    $logs = $item->PhanAnhLog();

                                    ?>
                                    <table class="table table-border dataTable" id="dataTableID">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Loại</th>
                                                <th>Nội dung</th>
                                                <th>Thời gian xử lý</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            foreach ($logs as $log) {
                                                $_log = new PhanAnhLog($log); 
                                            ?>
                                                <tr>
                                                    <td><?php echo $_log->Id; ?></td>
                                                    <td><?php echo $_log->Type; ?></td>
                                                    <td><?php echo $_log->Comment; ?></td>
                                                    <td><?php echo $_log->CreateRecord; ?></td>
                                                </tr>
                                            <?php
                                            }
                                            ?>
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>



                    </div>

                </div>
            </div>
        </div>
    </section>
</div>