<?php
$admin = new Module\user\Model\Admin($admin);
?>
<script type="text/javascript" >
    app.controller("usersController", function($scope, $http) {
        $scope.resetMail = function(id) {
            $http.post("/user/users/resetpassword/", $.param({"publicKey": id})).then(function(res) {
                $scope.thongBao = "đã reset password";
            });
        }
    });</script>

<ol class="breadcrumb">
    <li>
        <a href="/user/users/"  >
            Danh Sách Tài Khoản
        </a>
    </li>
    <li class="active" >
        Sửa
    </li>
</ol>
<div class="container-fluid" ng-controller="usersController" >
    <form action="" method="post" enctype="multipart/form-data" >
        <div class="row" >
            <section class="col-md-6 pb-10" >
                <div class="connectedSortable" >
                    <div class="box box-primary" >
                        <div class="box-header" >
                            <h3 class="box-title" >Tài Khoản</h3>
                        </div>
                        <div class="box-body" >
                            <div class="row">
                                <div class="col-md-6">
                                    <?php
                                    Module\user\Model\AdminForm::Id($admin->Id)->render();
                                    Module\user\Model\AdminForm::Name($admin->Name)->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-6">
                                    <?php
                                    Module\user\Model\AdminForm::Username($admin->Username)->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-6">
                                    <?php
                                    Module\user\Model\AdminForm::Email($admin->Email)->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-6">
                                    <?php
                                    Module\user\Model\AdminForm::Phone($admin->Phone)->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-6">
                                    <?php
                                    Module\user\Model\AdminForm::Address($admin->Address)->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-6">
                                    <?php
                                    Module\user\Model\AdminForm::Active($admin->Active)->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-6">
                                    <?php
                                    Module\user\Model\AdminForm::Groups($admin->Groups)->renderHTML();
                                    ?>
                                </div>
                                <div class="clearfix">

                                </div>
                                <div class="col-md-6 admin trungtambaohanh">
                                    <?php
                                    Module\user\Model\AdminForm::TrungTamBaoHanh($admin->TrungTamBaoHanh()->idKhachHang)->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-6 admin khachhang">
                                    <?php
                                    Module\user\Model\AdminForm::KhachHang($admin->KhachHang()->idKhachHang)->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-12">
                                    <?php
                                    Module\user\Model\AdminForm::Note($admin->Note)->renderHTML();
                                    ?>
                                </div>

                            </div>

                        </div>
                        <div class="box-footer" >
                            <input type="submit" class="btn-sm btn btn-success" value="Lưu" />
                        </div>
                    </div>
                </div>
            </section>
            <section class="col-md-6 pb-10" >
                <div class="connectedSortable" >
                    <div class="box box-primary" >
                        <div class="box-header" >
                            <h3 class="box-title" >Thao Tác</h3>
                        </div>
                        <div class="box-body" >
                            <input type="button" ng-click="resetMail('<?php echo $admin->publicKey(); ?>')" class="btn btn-success" value="Reset Password" />
                            {{thongBao}}
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </form>
</div>
<script>
    $(function() {
        var HienThiNhom = () => {
            console.log($("#Nhom").val());
            var idNhom = $("#Nhom").val();
            if (idNhom == '1' || idNhom == '2') {
                $(".admin").hide();
            }
            if (idNhom == '3') {
                $(".admin").hide();
                $(".khachhang").show();
            }
            if (idNhom == '4') {
                $(".admin").hide();
                $(".trungtambaohanh").show();
            }
        }
        $("#Nhom").change(() => {
            HienThiNhom();
        });
        $("#Nhom").each(() => {
            HienThiNhom();
        });
    });
</script>