<?php
$ModelAdmin = new Module\user\Model\Admin();
$name = !empty($_GET["keyword"]) ? $_GET["keyword"] : "";
$pagesIndex = !empty($_GET["pagesIndex"]) ? $_GET["pagesIndex"] : 1;
$pageNumber = !empty($_GET["pageNumber"]) ? $_GET["pageNumber"] : 10;
$tong = 0;
$TaiKhoans = $ModelAdmin->GetAllPT(["keyword" => $name, "Active" => [1, 2]], $pagesIndex, $pageNumber, $tong);
$linkPhanTrang = "/user/users/index/?pagesIndex=[i]&pageNumber={$pageNumber}&keyword={$name}";
?>
<div class=""  >
    <ol class="breadcrumb">
        <li><a href="#"  >Danh Sách Tài Khoản </a></li>
    </ol>
    <div class="container-fluid " >
        <section class="pb-10" >
            <div class="" >
                <div class="box box-primary" >
                    <div class="box-header" >
                        <div class="box-tools" >
                            <a href="/user/users/add" class="btn btn-sm btn-primary" >
                                <i class="fa fa-plus" ></i>
                                Thêm
                            </a>
                            <a class="btn btn-sm btn-primary" data-toggle="modal" href='#importExcell'>Import</a>
                            <button data-target="#TimKiem" class="btn btn-toggle btn-sm btn-primary" ><i class="fa fa-search-plus" ></i></button>
                        </div>
                        <h3 class="box-title" >Danh Sách Tài Khoản (<?php echo $tong; ?>)</h3>
                    </div>
                    <div class="box-body table-responsive" >
                        <div class="" id="TimKiem" >
                            <div class="form-inline">
                                <?php
                                Model\FormOptions::TimKiem($name, ["id" => "TuKhoa", "onchange" => "TimKiemSanPham()"])->render();
                                ?>
                            </div>
                        </div>
                        <table class="table table-bordered" >
                            <thead>
                                <tr class="bg-blue" >
                                    <th style="width: 90px;" >Action</th>
                                    <th class="text-center" style="width: 50px;" >#</th>
                                    <th>Tài Khoản</th>
                                    <th>Họ & Tên</th>
                                    <th>Email</th>
                                    <th>Nhóm</th>
                                    <th>SĐT</th>
                                    <th>Tình Trạng</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
//                                var_dump($TaiKhoans);
                                if ($TaiKhoans)
                                    foreach ($TaiKhoans as $k => $value) {
                                        $_Taikhoan = new Module\user\Model\Admin($value);
                                        ?>
                                        <tr >
                                            <th>
                                                <?php
                                                echo \Module\user\Model\AdminForm::LinkSua($_Taikhoan->Id);
                                                echo \Module\user\Model\AdminForm::LinkXoa($_Taikhoan->Id);
                                                ?>
                                            </th>
                                            <th class="text-center" ><?php echo \Common\Common::GetIndex($k, $pagesIndex, $pageNumber); ?></th>
                                            <th><?php echo $_Taikhoan->Username ?></th>
                                            <th><?php echo $_Taikhoan->Name; ?></th>
                                            <th><?php echo $_Taikhoan->Email ?></th>
                                            <th><?php echo $_Taikhoan->Groups()->Name ?></th>
                                            <th><?php echo $_Taikhoan->Phone ?></th>
                                            <th><?php echo $_Taikhoan->Active()->Name; ?></th>
                                        </tr>
                                        <?php
                                    }
                                ?>

                            </tbody>

                        </table>

                    </div>
                    <div class="box-footer" >
                        <div class="row">

                            <div class="col-md-1 col-sm-4 mt-10">
                                <?php
                                Model\FormOptions::HienThi($pageNumber, ["id" => "HienThi", "onchange" => "TimKiemSanPham()"])->render();
                                ?>
                            </div>
                            <div class="col-md-11 col-sm-8 ">
                                <?php
                                echo \Common\Common::PhanTrang(ceil($tong / $pageNumber), $pagesIndex, $linkPhanTrang);
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
<script type="text/javascript" >
    function TimKiemSanPham() {
        var path = "/user/users/index/?pagesIndex=1&pageNumber=[pn]&keyword=[key]";
        var tukhoa = $("#TuKhoa").val();
        var hienThi = $("#HienThi").val();
        path = path.replace('[pn]', hienThi);
        path = path.replace('[key]', tukhoa);
        window.location.href = path;
    }
</script>