<ol class="breadcrumb ">
    <li><a href="/dashboard/nhaptem/index">Danh Sanh Sách Nhập</a></li>
    <li><a>Xuất kho</a></li>
</ol>
<?php

use Model\FormOptions;
use Model\Obj2Html;
use Module\sanpham\Model\XuatNhapKho\FormPhieuXuatNhap;
use Module\user\Model\Admin;

$admin = Admin::getCurentUser(true);
$CodeQr = new \Model\CodeQR($admin->Username);
$ds = $CodeQr->GetCodes();
?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header" style="padding-top: 5px;">
                    <a class="btn btn-primary" href="/dashboard/nhaptem/">
                        <i class="fa fa-arrow-left"></i>
                    </a>
                    <h3 style="margin-left: 10px;line-height: 20px;" class="box-title">Xuất kho</h3>
                    <div class="box-tools pull-right">
                        <a href="/dashboard/nhaptem/scan" class="btn btn-primary"><i class="fa fa-camera"></i></a>
                    </div>
                </div>
                <div class="box-body">
                    <p style="color: red;">Chọn "Xác nhận" để ghi nhận thông tin nhân viên bán hàng, lý do xuất kho </p>
                    <form action="" method="POST">
                        <?php
                        $f = new FormPhieuXuatNhap();
                        ?>
                        <div class="row">
                            <div class="col-md-4">
                                <?php
                                $f->LyDoXuatKho()->renderHTML();
                                ?>
                            </div>
                            <div class="col-md-4">
                                <?php
                                $f->UserId()->renderHTML();
                                ?>
                            </div>
                            <div class="col-md-4">
                                <?php
                                $f->KhacHang()->renderHTML();
                                ?>
                            </div>
                            <div class="col-md-12">
                                <?php
                                $f->Content()->renderHTML();
                                ?>
                            </div>
                        </div>
                        <div class="text-right">
                            <button name="DoiTra" onclick="return confirm('Bạn có muốn xuất kho các sản phẩm này?')"
                                class="btn btn-sm btn-primary">
                                Xác nhận
                            </button>
                        </div>
                    </form>

                    <div class=" table-responsive">

                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th style="width: 50px">Stt</th>
                                    <th>Thông Tin Sản Phẩm</th>
                                </tr>
                            </thead>
                            <tbody id="DanhSachTem">
                                <?php
                                $index = 0;
                                if ($ds) {
                                    foreach ($ds as $k => $code) {
                                        $temSP = new \Module\sanpham\Model\TemSanPham($code);
                                        ?>
                                        <tr>
                                            <td>
                                                <?php echo 1 + $index++; ?>
                                            </td>
                                            <td>
                                                <?php
                                                Obj2Html::ThongTinSanPhamTheoMaTem($temSP->Code);
                                                ?>
                                            </td>
                                        </tr>
                                        <?php
                                    }
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>