<?php
$YeuCauSuas = Module\trungtambaohanh\Model\YeuCauBaoHanh::YeuCauSuaChuas();
?>
<ol class="breadcrumb">
    <li><a href="/dashboard/">Thông tin bảo hành</a></li>
</ol>
<div class="container-fluid ">
    <section class="pb-10 mt-20">
        <div class="connectedSortable">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Danh sách yêu cầu bảo hành</h3>
                </div>
                <div class="box-body table-responsive ">
                    <table class="table table-bordered table-striped  dataTable " id="data">
                        <thead>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th style="white-space: nowrap;">Name</th>
                                <th style="white-space: nowrap;">Khách Hàng</th>
                                <th style="white-space: nowrap;">Tỉnh Thành</th>
                                <th style="white-space: nowrap;">Thơi Gian Tạo</th>
                                <th style="white-space: nowrap;">Thời Gian Cập Nhật</th>
                                <th style="white-space: nowrap;">Tình Trạng</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($YeuCauSuas as $k => $op) {
                                $_Option = new Module\trungtambaohanh\Model\YeuCauBaoHanh($op);
                            ?>
                                <tr>
                                    <td><a href="/trungtambaohanh/yeucaubaohanh/index/#/<?php echo $_Option->Code ?>" class="btn btn-success">Chọn</a></td>
                                    <td><?php echo $k + 1; ?></td>
                                    <td>
                                        <?php
                                        echo $_Option->Name;
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                        echo $_Option->KhachHangTieuDung()->Name;
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                        echo $_Option->KhachHangTieuDung()->TinhThanh()->Name;
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                        echo Common\Common::ToDate($_Option->CreateDate);
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                        echo Common\Common::ToDate($_Option->UpdateDate);
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                        echo $_Option->Status();
                                        ?>
                                    </td>
                                </tr>
                            <?php
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</div>