<?php
$YeuCauSuas = Module\trungtambaohanh\Model\YeuCauBaoHanh::YeuCauSuaChuas();
?>

<div class="row " >
    <section class="col-md-12 mb-10" >
        <a class="btn btn-primary" href='/dashboard/'>Danh Sách Công Việc</a>
    </section>
    <section class="col-md-12 pb-10 mt-20" >
        <div class="connectedSortable" >
            <div class="box box-primary" >
                <div class="box-body table-responsive" >
                    <table class="table table-bordered dataTable " id="data"   >
                        <thead>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Name</th>
                                <th>Thơi Gian Tạo</th>
                                <th>Thời Gian Cập Nhật</th>
                                <th>Tình Trạng</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($YeuCauSuas as $k => $op) {
                                $_Option = new Module\trungtambaohanh\Model\YeuCauBaoHanh($op);
                                ?>
                                <tr>
                                    <td><a href="/trungtambaohanh/yeucaubaohanh/index/#/<?php echo $_Option->Code ?>" class="btn btn-success" >Chọn</a></td>
                                    <td><?php echo $k + 1; ?></td>
                                    <td>
                                        <?php
                                        echo $_Option->Name;
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                        echo Common\Common::ToDate($_Option->CreateDate);
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                        echo Common\Common::ToDate($_Option->UpdateDate);
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                        echo $_Option->Status();
                                        ?>
                                    </td>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Name</th>
                                <th>Thơi Gian Tạo</th>
                                <th>Thời Gian Cập Nhật</th>
                                <th>Tình Trạng</th>
                            </tr>
                        </tfoot>

                    </table>
                </div>
            </div>

        </div>
    </section>
</div>