<?php

use Common\Common;
use Datatable\Response;
use Datatable\Table;
use Model\FormRender;
use Module\trungtambaohanh\Model\YeuCauBaoHanh;
use Module\user\Model\Admin;
use PFBC\Element\Hidden;
use PFBC\Element\Select;
use PFBC\Element\Textbox;

$y = new YeuCauBaoHanh();
$TableName = table_prefix . "yeucaubaohanh";
$items = $y->runsqlToArray("select `Status`, count(*) as  `Tong` from {$TableName} Group by `Status` order by `Status` DESC");

// $YeuCauSuas = new YeuCauBaoHanh();
// $total = 0;
// $pageIndex = intval($_REQUEST["indexPage"] ?? "1");
$params["pageSize"] = intval($_REQUEST["pageSize"] ?? 10);
$params["Status"] = Common::CheckInput($_REQUEST["Status"] ?? "");
$params["Keyword"] = $_REQUEST["Keyword"] ?? "";
// $items = $YeuCauSuas->GetItems($params, $pageIndex, $params["pageSize"], $total);
// $response = new Response();
// $response->params = $params;
// $response->totalrows = $total;
// $response->number = $params["pageSize"];
// $response->indexPage = $pageIndex;
// $response->totalPage = ceil($total / $params["pageSize"]);
// $response->rows = $items;
// $response->status = Response::OK;
// $response->columns = [
//     "Actions" => "Thao Tác",
//     "Status" => "Tình Trạng",
//     "TinhThanh" => "Tỉnh Thành",
//     "QuanHuyen" => "Quận Huyện",
//     "DiaChi" => "Địa Chỉ",
//     "SDT" => "SĐT",
//     "KhachHangTieuDung" => "Mã khách hàng",
//     "MaTem" => "Mã Tem",
//     "CreateDate" => "Ngày tạo yêu cầu",
//     "NgayBaoHanh" => "Ngày yêu cầu bảo hành",
//     "NgayThucHien" => "Ngày thực hiện",
//     "NoiDung" => "Nội dung",
// ];
// $response = $response->ToRow();

$fpageIndex = new FormRender(new Hidden("pageIndex", 1));
$fpageSize = new FormRender(new Hidden("pageSize", $params["pageSize"]));
$fKeyword = new FormRender(new Textbox("Từ khóa", "Keyword", [
    "class" => "form-control",
    "onchange" => "submit()",
    "placeholder" => "SĐT...",
    "value" => Common::CheckInput($_REQUEST["Keyword"] ?? "")
]));

$fTinhTrang = new FormRender(
    new Select(
        "Tình Trạng",
        "Status",
        ["" => "Tất cả"] + YeuCauBaoHanh::ListStatus(),
        [
            "class" => "form-control",
            "onchange" => "submit()",
            "value" => $params["Status"]
        ]
    )
);

?>
<ol class="hidden-sm hidden-xs breadcrumb" style="margin-bottom: 5px;">
    <li><a href="/dashboard/">Yêu cầu bảo hành</a></li>
</ol>
<div class="container-fluid ">
    <section class=" ">
        <div class="">
            <?php
            if (Admin::CheckQuyen([Admin::Admin]) == false) {
                ?>
                <div class="box-primary mt-10">
                    <div class="box-body ">
                        <div class="row">
                            <div class="col-md-1 col-xs-4">
                                <div class="row">
                                    <?php
                                    if (Admin::CheckQuyen([Admin::Admin, Admin::SuperAdmin, Admin::NVKT]) == true) {
                                        ?>
                                        <a href="/dashboard/kiemhang/" class="btn-chucnang">
                                            <div class="btn "><i class="fa fa-camera fa-3x"></i></div>
                                            <span> Kiểm hàng</span>
                                        </a>
                                        <?php
                                    }
                                    ?>
                                </div>
                            </div>
                            <div class="col-md-1 col-xs-4">
                                <div class="row">
                                    <a href="/trungtambaohanh/yeucaubaohanh/scan/" class="btn-chucnang">
                                        <div class="btn "><i class="fa fa-camera fa-3x"></i></div>
                                        <span> Bảo hành</span>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-1 col-xs-4">
                                <div class="row">
                                    <a href="/dashboard/index/baohanh/" class="btn-chucnang">
                                        <div class="btn "><i class="fa fa-list fa-3x"></i></div>
                                        <span>Y/C Bảo hành</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php
            }
            ?>
            <h4>Yêu cầu bảo hành</h4>
            <div class="row">
                <?php
                foreach ($items as $k => $v) {
                    ?>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-aqua"><i class="ion ion-ios-gear-outline"></i></span>
                            <div class="info-box-content">
                                <span class="info-box-text"><?php echo YeuCauBaoHanh::ListStatus()[$v['Status']] ?></span>
                                <span class="info-box-number"><?php echo $v['Tong'] ?></span>
                            </div>
                        </div>
                    </div>
                    <?php

                }
                ?>
            </div>

            <!-- <form action="/dashboard/index/index/" method="get">
                <div class="row">
                    <div class="col-md-2 col-xs-6">
                        <?php
                        $fKeyword->renderHTML();
                        ?>
                    </div>
                    <div class="col-md-2 col-xs-6">
                        <?php
                        $fpageIndex->render();
                        $fpageSize->render();
                        $fTinhTrang->renderHTML();
                        ?>
                    </div>
                </div>
            </form>
            <div class="box box-primary">
                <div class="box-header">
                    <div class="box-tools">
                    </div>
                    <h3 class="box-title">Yêu cầu bảo hành</h3>
                </div>
                <div class="box-body table-responsive ">

                    <?php
                    $link = "/dashboard/index/index/";
                    // $dataTable = new Table(["rows" => $data["rows"], "columns" => $columns], Card::class);
                    $dataTable = new Table([
                        "rows" => $response["rows"],
                        "columns" => $response["columns"]
                    ], YeuCauBaoHanh::class, true);
                    $dataTable->setPropTable(
                        [
                            "table" => ["id" => "table", "class" => "table table-border"],
                            "thead" => ["class" => "bg-primary"],
                        ]
                    );
                    $dataTable->RenderHtml();
                    echo $dataTable->PaginationWidthData($response, $link);
                    ?>
                </div>
            </div> -->
        </div>
    </section>
</div>
<style>
    .btn-chucnang {
        text-align: center;

    }

    .btn-chucnang span {
        font-size: 1em;
        text-align: center;
        color: #000 !important;
        margin: auto;
        display: block;
        padding-top: 10px;
    }

    .btn-chucnang .btn {
        border-radius: 7px;
        padding: 5px;
        display: table;
        margin: auto;

        background: #fff !important;
        color: #3C8DBC !important;
        width: 70px;
        height: 50px;
        line-height: 30px;
        box-shadow: 1px 1px 10px #aaa;
    }
</style>