<script src="/public/tmd/testController.js" ></script>
<section class="content" ng-controller="testController" >
<div class="container" >
    <form action=""> 
        <input placeholder="Họ và Tên" type="text" ng-model="hoTen" > 
        <fieldset>
            <legend>infor</legend>
            <input placeholder="" type="text" ng-model="infor.hoTen" > 
        </fieldset> 
    </form> 
</div> 
</section>
