<sub-menu></sub-menu>
<div class="row " >
    <section class="col-md-12 mb-10" >
        <a class="btn btn-primary" href='/dashboard/'>Danh Sách Công Việc</a>
    </section>
    <section class="col-md-12 pb-10 mt-20" >
        <div class="connectedSortable" >
            <div class="box box-primary" >
                <div class="box-body table-responsive" >
                    <table class="table table-bordered dataTable " id="data"   >
                        <thead>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Name</th>
                                <th>Thơi Gian Tạo</th>
                                <th>Thời Gian Cập Nhật</th>
                                <th>Tình Trạng</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Name</th>
                                <th>Thơi Gian Tạo</th>
                                <th>Thời Gian Cập Nhật</th>
                                <th>Tình Trạng</th>
                            </tr>

                        </tbody>
                        <tfoot>
                            <tr>
                                <th></th>
                                <th>#</th>
                                <th>Name</th>
                                <th>Thơi Gian Tạo</th>
                                <th>Thời Gian Cập Nhật</th>
                                <th>Tình Trạng</th>
                            </tr>
                        </tfoot>

                    </table>
                </div>
            </div>

        </div>
    </section>
</div>