<?php

use Common\Common;
use Model\FormOptions;
use Model\FormRender;

$aLink = [
    [
        "Id" => "1",
        "Link" => "/dashboard/baocao/baocao1/",
        "LinkDownload" => "/data/baocao1.xlsx",
        "Name" => "Báo cáo về danh sách tem kích hoạt",
        "Icon" => "",
        "Optiops" => [
            "ThoiGianKichHoat" => "Thời gian kích hoạt",
            "ThoiGianHetBaoHang" => "Thời gian hết bảo hành"
        ],
        "Prop" => [
            "label" => "Loại Ngày",
            "class" => "form-control"
        ]
    ],
    [
        "Id" => "4",
        "Link" => "/dashboard/baocao/baocao4/",
        "LinkDownload" => "/data/baocao4.xlsx",
        "Name" => "Báo cáo danh sách thông tin người sử dụng",
        "Icon" => "",
        "Optiops" => [
            "ThoiGianKichHoat" => "Thời gian người sử dụng kích hoạt",
            "ThơiGianHetBaoHanh" => "Thời gian hết bảo hành",
        ],
        "Prop" => [
            "label" => "Loại Ngày",
            "class" => "form-control"
        ]
    ],
    // [
    //     "Id" => "5",
    //     "Link" => "/dashboard/baocao/baocao5/",
    //     "Name" => "Báo cáo về thông tin bảo hành sản phẩm phản hồi từ khách hàng",
    //     "Icon" => "",
    // ],
    // [
    //     "Link" => "/dashboard/baocao/baocao6/",
    //     "Name" => "Báo cáo danh sách thông tin khách hàng đại lý đã phát sinh đơn hàng",
    //     "Icon" => "",
    // ],
    [
        "Id" => "7",
        "Link" => "/dashboard/baocao/baocao7/",
        "LinkDownload" => "/data/baocao7.xlsx",
        "Name" => "Báo cáo danh sách số lượng tem chưa kích hoạt",
        "Icon" => "",
        "Optiops" => [
            "BaoMaSanPham" => "Thời gian khi báo mã SP"
        ],
        "Prop" => [
            "label" => "Loại Ngày",
            "class" => "form-control"
        ]

    ],
    [
        "Id" => "8",
        "Link" => "/dashboard/baocao/baocao8/",
        "LinkDownload" => "/data/baocao8.xlsx",
        "Name" => "Báo cáo đổi trả",
        "Icon" => "",
        "Optiops" => [
            "BaoMaSanPham" => "Thời gian tạo phiếu"
        ],
        "Prop" => [
            "label" => "",
            "class" => "form-control"
        ]

    ],
];
// echo Common::GetLastDateOfMonth();
$fromDate = date("Y-m-01", time());
$toDate = Common::GetLastDateOfMonth();
?>
<ol class="breadcrumb" style="margin-bottom: 0px;">
    <li>
        <a href="/dashboard/">Dashboard</a>
    </li>
    <li class="active">Báo Cáo</li>
</ol>
<div class="container-fluid ">
    <div class="row">
        <section class="pb-10">
            <div class="connectedSortable">
                <div class="box box-primary">
                    <div class="box-header">
                        <h2 class="box-title">
                            Danh sách báo cáo
                        </h2>
                    </div>
                    <div class="box-body">
                        <table class="table table-bordered">
                            <?php
                            foreach ($aLink as $key => $value) {
                                ?>
                                <tr>
                                    <td class="text-center">
                                        <?php echo $key + 1 ?>
                                    </td>
                                    <td>
                                        <form method="POST" data-linkdownload="<?php echo $value["LinkDownload"]; ?>"
                                            style="margin-bottom: 0px;" class="form-group"
                                            action="<?php echo $value["Link"]; ?>">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <strong>
                                                        <?php echo $value["Name"]; ?>
                                                    </strong>
                                                </div>
                                                <div class="col-md-3 col-xs-6">
                                                    <div class="form-group">
                                                        <label>Từ ngày</label>
                                                        <input value="<?php echo $fromDate; ?>" name="fromDate" type="date"
                                                            class="form-control">
                                                    </div>
                                                </div>
                                                <div class="col-md-3 col-xs-6">
                                                    <div class="form-group">
                                                        <label>Đến ngày</label>
                                                        <input value="<?php echo $toDate; ?>" name="toDate" type="date"
                                                            class="form-control">
                                                    </div>
                                                </div>
                                                <div class="col-md-3 col-xs-6">
                                                    <div class="form-group">

                                                        <?php
                                                        FormOptions::Select("Loại ngày", "DateType", $value["Optiops"] ?? [], $value["Prop"] ?? [])->renderHTML();
                                                        ?>
                                                    </div>
                                                </div>
                                                <div class="col-md-3 col-xs-6">
                                                    <div class="form-group">
                                                        <label>&nbsp;</label>
                                                        <div class="row">
                                                            <button type="submit" class="btn btn-success">Gửi</button>
                                                            <!-- <a data-linkdownload="<?php echo $value["LinkDownload"]; ?>"
                                                                class="downloadAjax btn btn-primary"
                                                                href="<?php echo $value["Link"]; ?>">
                                                                <i class="fa fa-download" aria-hidden="true"></i>
                                                                Tất cả
                                                            </a> -->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </td>
                                </tr>
                                <?php
                            }
                            ?>
                        </table>
                    </div>
                </div>
            </div>
        </section>
        <div class="modal fade" id="modal-id">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Đang Tải...</h4>
                    </div>
                    <div class="modal-body">
                        <img style="margin: auto;height: 100px;" src="/public/loading.svg" class="img img-responsive">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $("form").submit(function (e) {
            $("#modal-id").modal("show");
            var dataFormString = $(this).serialize();
            var action = $(this).attr("action");
            var linkdownload = $(this).data("linkdownload");
            //  console.log(linkdownload);
            $.ajax({
                url: `${action}`,
                type: 'GET',
                data: dataFormString,
                contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                success: function (response) {
                    if (response.url) {
                        window.open(response.url);
                    } else {
                        window.open(linkdownload);
                    }
                    $("#modal-id").modal('toggle');
                },
                error: function () {
                    // console.log('Loi');
                    // window.open(linkdownload);
                }
            }).done(function () {
                // console.log('Loi');
                // window.open(linkdownload);
            });
            return false;
        });

        $(".downloadAjax").click(function (e) {
            $("#modal-id").modal("show");
            var linkdownload = $(this).data("linkdownload");
            e.preventDefault();
            var link = $(this).attr('href');
            $.ajax({
                url: link,
            }).done(function (res) {
                $("#modal-id").modal('toggle');
                //  $("#modal-id").toggle();
                window.open(linkdownload);
            })
        });
    });
</script>