<script type="text/javascript" >
    app.controller("connectController", function($scope, $http) {
        $scope.connectInnit = function( ) {
            $http.get("/project/api/projects/").then(function(res) {
                $scope._Project = res.data;
            });
        }
    });
</script>
<div class="row " ng-controller="connectController" ng-init="projectInnit()" >
    <section class="col-md-12 pb-10" >
        <div class="connectedSortable" >
            <div class="box box-primary" >
                <div class="box-header" >
                    <h3 class="box-title" >Liên Kết Mạng Xã Hội</h3>
                </div>
                <div class="box-body" >
                    <div class="col-lg-3 col-xs-6">
                        <div class="small-box bg-aqua">
                            <div class="inner">
                                <h3>Facebook</h3>
                                <p>Kết nối Pixel facebook</p>
                            </div>
                            <div class="icon">
                                <i class="fa fa-facebook"></i>
                            </div>
                            <a href="/project/pixelfacebook" class="small-box-footer">Chi tiết <i class="fa fa-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>