
<script src="<?php echo AppPath; ?>/public/historyphieuhen/lichsuphieuhenController.js" type="text/javascript"></script>
<div class="clearfix" style="clear: both;" ></div>
<div class="container" id="lichsuController" ng-controller="lichsuphieuhenController" ng-init="lichsuphieuhenframeInit()"   >
    <div ng-bind-html="trustAsHtml(_LinkIframe)"  style="min-height: 500px;width: 100%;" ></div>
</div>