<?php
$User = \Module\user\Model\Admin::getCurentUser();
?>
<div class="container" style="margin-top: 20px;" >
    <div class="col-xs-12 col-lg-8 col-sm-12 col-md-8" style="padding-right   : 0px;">
        <div class="panel panel-primary">
            <div class="panel-heading ">
                <h3 class="panel-title">Thông Tin Chung</h3>
            </div>
            <div class="panel-body">
                <form method="POST" action="/user/profile/saveprofile/" >
                    <div class="form-group col-lg-6 col-md-6 " >
                        <label>Username</label>
                        <input readonly="" disabled="disabled" value="<?php echo $User['Username'] ?>" class="form-control"  >
                    </div>
                    <div class="form-group col-lg-6 col-md-6 " >
                        <label>Họ Tên</label>
                        <input name="User[Name]" placeholder="Name" value="<?php echo $User['Name'] ?>" class="form-control"  >
                    </div>
                    <div class="form-group col-lg-6 col-md-6 " >
                        <label>SDT</label>
                        <input name="User[Phone]" placeholder="Phone" value="<?php echo $User['Phone'] ?>" class="form-control"  >
                    </div>
                    <div class="form-group col-lg-6 col-md-6 " >
                        <label>Email</label>
                        <input name="User[Email]" placeholder="Email" value="<?php echo $User['Email'] ?>" class="form-control"  >
                    </div>
                    <div class="form-group col-md-12 " >
                        <label>Địa Chỉ</label>
                        <textarea name="User[Address]" placeholder="Address" class="form-control"><?php echo $User['Address'] ?></textarea>
                    </div>
                    <div class="clearfix" ></div>
                    <div class="form-group col-lg-6 col-md-6 " >
                        <div class="form-group">
                            <label>&nbsp;</label>
                            <input value="Lưu" type="submit" name="SuaThongTinChung" class="btn btn-sm btn-primary " />
                            <input value="Làm Lại" type="reset"  class="btn btn-sm btn-default " />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-lg-4 col-sm-12 col-md-4" style="">
        <div class="panel panel-primary ">
            <div class="panel-heading">
                <h3 class="panel-title">Bảo Mật</h3>
            </div>
            <div class="panel-body">
                <form method="POST" action="/user/profile/saveprofile/" >
                    <div class="form-group">
                        <label>Mật Khẩu Cũ</label>
                        <input required="required" name="User[OdlPassword]" type="password" value="" class="form-control"  >
                    </div>
                    <div class="form-group">
                        <label>Mật Khẩu Mới</label>
                        <input required="required" name="User[NewPassword]" type="password" value="" class="form-control"  >
                    </div>
                    <div class="form-group">
                        <label>nhập lại Mật Khẩu</label>
                        <input required="required" name="User[RePassword]" type="password" value="" class="form-control"  >
                    </div>
                    <div class="form-group">
                        <label>&nbsp;</label>
                        <input value="Lưu" type="submit" name="SuaPassword" class="btn btn-primary" />

                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
